package main

import (
    "fmt"
    "os"
    "path/filepath"
    "strings"
)

// EmitGo writes one *_test.go per bb-package (testpkg, bitwid) under outDir.
// outDir must be the per-language root (e.g. e2e/tests/go/).
func EmitGo(spec *Spec, outDir string) error {
    if err := os.MkdirAll(outDir, 0o755); err != nil {
        return err
    }

    byPkg := map[string][]Scenario{}
    for _, sc := range spec.Scenarios {
        byPkg[sc.Package] = append(byPkg[sc.Package], sc)
    }

    for pkg, scs := range byPkg {
        var sb strings.Builder
        emitGo_header(&sb, pkg)
        for _, sc := range scs {
            sb.WriteString(emitGo_scenario(sc))
            sb.WriteString("\n")
        }
        path := filepath.Join(outDir, pkg, pkg+"_test.go")
        if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
            return err
        }
        if err := os.WriteFile(path, []byte(sb.String()), 0o644); err != nil {
            return err
        }
    }
    return nil
}

func emitGo_header(sb *strings.Builder, pkg string) {
    sb.WriteString("// Bubbler E2E Test - Go target\n")
    sb.WriteString("//\n")
    sb.WriteString("// GENERATED by e2e/spec; DO NOT EDIT BY HAND.\n")
    sb.WriteString("// Source of truth: e2e/spec/scenarios.go\n")
    fmt.Fprintf(sb, "package %s\n\n", pkg)
    sb.WriteString("import (\n")
    sb.WriteString("    \"bytes\"\n")
    sb.WriteString("    \"math\"\n")
    sb.WriteString("    \"testing\"\n")
    sb.WriteString(")\n\n")
    sb.WriteString("// Helpers — kept local so each package's *_test.go is self-contained.\n")
    sb.WriteString("func nearF64_(a, b, eps float64) bool { return math.Abs(a-b) < eps }\n")
    sb.WriteString("func nearF32_(a, b, eps float32) bool { return math.Abs(float64(a-b)) < float64(eps) }\n")
    sb.WriteString("var _ = bytes.Equal // keep import even when no scenario uses []byte\n\n")
}

func emitGo_scenario(sc Scenario) string {
    if sc.StructName == "GetterSetter" {
        return emitGo_getterSetter(sc)
    }
    var sb strings.Builder
    fmt.Fprintf(&sb, "// %s — %s\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, "func Test%s(t *testing.T) {\n", sc.StructName)

    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "    t.Run(%q, func(t *testing.T) {\n", c.Name)

        // Build setup struct via composite literal where convenient. For mixed
        // setups (struct + arrays + bytes) we emit per-field assignments after
        // a zero literal.
        fmt.Fprintf(&sb, "        var s %s\n", sc.StructName)
        for _, fv := range c.Setup {
            sb.WriteString(emitGo_assignVal("s."+pascalCase(fv.Name), fv.V, "        "))
        }

        sb.WriteString("        buf := s.Encode()\n")
        if !sc.IsDynamic {
            fmt.Fprintf(&sb, "        if int(s.Size()) != len(buf) { t.Fatalf(\"encode size = %%d, want %%d\", len(buf), s.Size()) }\n")
        }

        if sc.StructName == "BigEndianFields" {
            sb.WriteString("        if buf[0] != 0xBE { t.Errorf(\"buf[0]: got 0x%X\", buf[0]) }\n")
            sb.WriteString("        if buf[1] != 0x12 || buf[2] != 0x34 { t.Errorf(\"u16 BE: 0x%02X 0x%02X\", buf[1], buf[2]) }\n")
        }
        if sc.StructName == "ConstantFields" {
            sb.WriteString("        if buf[0] != 0xAA { t.Errorf(\"header: 0x%X\", buf[0]) }\n")
            sb.WriteString("        if buf[1] != 0x02 { t.Errorf(\"version: 0x%X\", buf[1]) }\n")
            sb.WriteString("        if buf[4] != 0x02 { t.Errorf(\"magic_color: 0x%X\", buf[4]) }\n")
        }

        fmt.Fprintf(&sb, "        var d %s\n", sc.StructName)
        sb.WriteString("        n := d.Decode(buf)\n")
        if sc.IsDynamic {
            sb.WriteString("        if n <= 0 { t.Fatalf(\"Decode returned %d\", n) }\n")
        } else {
            sb.WriteString("        if n != int(d.Size()) { t.Fatalf(\"Decode = %d, want %d\", n, d.Size()) }\n")
        }
        for _, af := range c.resolveAssert() {
            sb.WriteString(emitGo_assertVal("d."+pascalCase(af.Name), af.V, af.Tol, "        "))
        }

        for _, e := range c.Errors {
            fmt.Fprintf(&sb, "        // decode-error: %s\n", e.Name)
            sb.WriteString("        {\n")
            sb.WriteString("            bad := append([]byte(nil), buf...)\n")
            for _, p := range e.Patches {
                fmt.Fprintf(&sb, "            bad[%d] = 0x%02X\n", p.Offset, p.Value)
            }
            fmt.Fprintf(&sb, "            var err %s\n", sc.StructName)
            fmt.Fprintf(&sb, "            if got := err.Decode(bad); got != %d { t.Errorf(\"%s: decode = %%d, want %d\", got) }\n",
                e.ExpectedRet, e.Name, e.ExpectedRet)
            sb.WriteString("        }\n")
        }
        sb.WriteString("    })\n")
    }

    if len(sc.DecodeSizeChecks) > 0 {
        sb.WriteString(emitGo_decodeSize(sc))
    }
    sb.WriteString("}\n")
    return sb.String()
}

func emitGo_assignVal(dst string, v Val, indent string) string {
    switch v.Kind {
    case VKBool:
        return fmt.Sprintf("%s%s = %s\n", indent, dst, goBool(v))
    case VKU8, VKU16, VKU32, VKU64, VKI8, VKI16, VKI32, VKI64:
        return fmt.Sprintf("%s%s = %s\n", indent, dst, goIntLit(v))
    case VKF32:
        return fmt.Sprintf("%s%s = math.Float32frombits(0x%08X)\n", indent, dst, uint32(v.U))
    case VKF64:
        return fmt.Sprintf("%s%s = math.Float64frombits(0x%016X)\n", indent, dst, v.U)
    case VKEnum:
        return fmt.Sprintf("%s%s = %s\n", indent, dst, v.EnumName)
    case VKString:
        return fmt.Sprintf("%s%s = %s\n", indent, dst, goStringLit(v.Str))
    case VKBytes:
        if len(v.Bytes) == 0 {
            return fmt.Sprintf("%s%s = nil\n", indent, dst)
        }
        return fmt.Sprintf("%s%s = []byte{%s}\n", indent, dst, goByteList(v.Bytes))
    case VKStruct:
        var sb strings.Builder
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitGo_assignVal(dst+"."+pascalCase(f.Name), f.V, indent))
        }
        return sb.String()
    case VKArray:
        var sb strings.Builder
        for i, item := range v.Array.Items {
            sb.WriteString(emitGo_assignVal(fmt.Sprintf("%s[%d]", dst, i), item, indent))
        }
        return sb.String()
    }
    return ""
}

func emitGo_assertVal(dst string, v Val, tol float64, indent string) string {
    switch v.Kind {
    case VKBool:
        return fmt.Sprintf("%sif %s != %s { t.Errorf(%q+\": got %%v\", %s) }\n",
            indent, dst, goBool(v), dst, dst)
    case VKU8, VKU16, VKU32, VKU64, VKI8, VKI16, VKI32, VKI64:
        return fmt.Sprintf("%sif %s != %s { t.Errorf(%q+\": got %%v\", %s) }\n",
            indent, dst, goIntLit(v), dst, dst)
    case VKF32:
        if tol > 0 {
            return fmt.Sprintf("%sif !nearF32_(%s, math.Float32frombits(0x%08X), %g) { t.Errorf(%q+\": got %%v\", %s) }\n",
                indent, dst, uint32(v.U), float32(tol), dst, dst)
        }
        return fmt.Sprintf("%sif math.Float32bits(%s) != 0x%08X { t.Errorf(%q+\": bits got 0x%%08X\", math.Float32bits(%s)) }\n",
            indent, dst, uint32(v.U), dst, dst)
    case VKF64:
        if tol > 0 {
            return fmt.Sprintf("%sif !nearF64_(%s, math.Float64frombits(0x%016X), %g) { t.Errorf(%q+\": got %%v\", %s) }\n",
                indent, dst, v.U, tol, dst, dst)
        }
        return fmt.Sprintf("%sif math.Float64bits(%s) != 0x%016X { t.Errorf(%q+\": bits got 0x%%016X\", math.Float64bits(%s)) }\n",
            indent, dst, v.U, dst, dst)
    case VKEnum:
        return fmt.Sprintf("%sif %s != %s { t.Errorf(%q+\": got %%v\", %s) }\n",
            indent, dst, v.EnumName, dst, dst)
    case VKString:
        return fmt.Sprintf("%sif %s != %s { t.Errorf(%q+\": got %%q\", %s) }\n",
            indent, dst, goStringLit(v.Str), dst, dst)
    case VKBytes:
        if len(v.Bytes) == 0 {
            return fmt.Sprintf("%sif len(%s) != 0 { t.Errorf(%q+\": got %%v\", %s) }\n",
                indent, dst, dst, dst)
        }
        return fmt.Sprintf("%sif !bytes.Equal(%s, []byte{%s}) { t.Errorf(%q+\": got %%v\", %s) }\n",
            indent, dst, goByteList(v.Bytes), dst, dst)
    case VKStruct:
        var sb strings.Builder
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitGo_assertVal(dst+"."+pascalCase(f.Name), f.V, tol, indent))
        }
        return sb.String()
    case VKArray:
        var sb strings.Builder
        for i, it := range v.Array.Items {
            sb.WriteString(emitGo_assertVal(fmt.Sprintf("%s[%d]", dst, i), it, tol, indent))
        }
        return sb.String()
    }
    return ""
}

func emitGo_decodeSize(sc Scenario) string {
    var sb strings.Builder
    sb.WriteString("    t.Run(\"decode_size\", func(t *testing.T) {\n")

    var needSource bool
    var srcCase string
    for _, ds := range sc.DecodeSizeChecks {
        if ds.SourceCase != "" {
            needSource = true
            srcCase = ds.SourceCase
        }
    }
    if needSource {
        var c Case
        for _, cc := range sc.Cases {
            if cc.Name == srcCase {
                c = cc
                break
            }
        }
        fmt.Fprintf(&sb, "        var src %s\n", sc.StructName)
        for _, fv := range c.Setup {
            sb.WriteString(emitGo_assignVal("src."+pascalCase(fv.Name), fv.V, "        "))
        }
        sb.WriteString("        full := src.Encode()\n")
    }

    fmt.Fprintf(&sb, "        var d %s\n", sc.StructName)
    for _, ds := range sc.DecodeSizeChecks {
        fmt.Fprintf(&sb, "        // %s\n", ds.Name)
        if ds.SourceCase != "" {
            if ds.Truncate == 0 {
                sb.WriteString("        if got := d.DecodeSize(full); got != len(full) { t.Errorf(\"complete: got %d, want %d\", got, len(full)) }\n")
            } else {
                fmt.Fprintf(&sb, "        if got := d.DecodeSize(full[:len(full)-%d]); got != -len(full) { t.Errorf(\"truncate: got %%d, want %%d\", got, -len(full)) }\n", ds.Truncate)
            }
        } else {
            fmt.Fprintf(&sb, "        if got := d.DecodeSize([]byte{%s}); got != %d { t.Errorf(%q+\": got %%d, want %d\", got) }\n",
                goByteList(ds.Bytes), ds.Expected, ds.Name, ds.Expected)
        }
    }
    sb.WriteString("    })\n")
    return sb.String()
}

func emitGo_getterSetter(sc Scenario) string {
    var sb strings.Builder
    fmt.Fprintf(&sb, "// %s — %s\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, "func Test%s(t *testing.T) {\n", sc.StructName)
    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "    t.Run(%q, func(t *testing.T) {\n", c.Name)
        fmt.Fprintf(&sb, "        var s %s\n", sc.StructName)
        for _, ap := range c.Accessors {
            fmt.Fprintf(&sb, "        s.Set%s(math.Float64frombits(0x%016X))\n",
                pascalCase(ap.SetterName), ap.SetArg.U)
        }
        roundTrip := false
        for _, ap := range c.Accessors {
            if !ap.NoRoundTrip {
                roundTrip = true
                break
            }
        }
        if roundTrip {
            sb.WriteString("        buf := s.Encode()\n")
            fmt.Fprintf(&sb, "        var d %s\n", sc.StructName)
            sb.WriteString("        if d.Decode(buf) < 0 { t.Fatalf(\"decode failed\") }\n")
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "        if !nearF64_(d.Get%s(), math.Float64frombits(0x%016X), %g) { t.Errorf(\"%s: got %%v\", d.Get%s()) }\n",
                    pascalCase(ap.GetterName), ap.Expected.U, tol, ap.GetterName, pascalCase(ap.GetterName))
            }
        } else {
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "        if !nearF64_(s.Get%s(), math.Float64frombits(0x%016X), %g) { t.Errorf(\"%s: got %%v\", s.Get%s()) }\n",
                    pascalCase(ap.GetterName), ap.Expected.U, tol, ap.GetterName, pascalCase(ap.GetterName))
            }
        }
        sb.WriteString("    })\n")
    }
    sb.WriteString("}\n")
    return sb.String()
}

// ──────────────────────────────────────────────────────────────────────────
// Value formatting
// ──────────────────────────────────────────────────────────────────────────

func goBool(v Val) string {
    if v.U != 0 {
        return "true"
    }
    return "false"
}

func goIntLit(v Val) string {
    switch v.Kind {
    case VKU8, VKU16, VKU32, VKU64:
        return fmt.Sprintf("0x%X", v.U)
    case VKI8, VKI16, VKI32, VKI64:
        return fmt.Sprintf("%d", v.I)
    }
    return ""
}

func goStringLit(s string) string {
    var sb strings.Builder
    sb.WriteByte('"')
    for _, r := range s {
        switch r {
        case '\\':
            sb.WriteString("\\\\")
        case '"':
            sb.WriteString("\\\"")
        case '\n':
            sb.WriteString("\\n")
        case '\r':
            sb.WriteString("\\r")
        case '\t':
            sb.WriteString("\\t")
        default:
            if r < 0x20 {
                fmt.Fprintf(&sb, "\\u%04x", r)
            } else {
                sb.WriteRune(r)
            }
        }
    }
    sb.WriteByte('"')
    return sb.String()
}

func goByteList(b []byte) string {
    parts := make([]string, len(b))
    for i, v := range b {
        parts[i] = fmt.Sprintf("0x%02X", v)
    }
    return strings.Join(parts, ", ")
}
