package main

import (
    "fmt"
    "strings"
)

// EmitCsharp produces e2e/tests/csharp/Program.cs.
//
// The generated code uses top-level statements and works on both net8.0 and
// net472. Float bit-level helpers are spelled out using BitConverter.GetBytes
// rather than SingleToInt32Bits so net472 compiles too. The DynamicFields
// `Data` property type changes between byte[] / Memory<byte> based on -memcpy,
// so we keep the reflective helper that the previous hand-written driver had.
func EmitCsharp(spec *Spec) string {
    var sb strings.Builder

    sb.WriteString(`/*
 * Bubbler E2E Test - C# target
 *
 * GENERATED by e2e/spec; DO NOT EDIT BY HAND.
 * Source of truth: e2e/spec/scenarios.go
 */
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Testpkg;
using Bitwid;

int pass = 0, fail = 0;
string current = "";

void Check(bool cond, string msg) {
    if (cond) { pass++; }
    else {
        Console.Error.WriteLine($"  FAIL [{current}] {msg}");
        fail++;
    }
}

void CheckEq<T>(T a, T b, string msg)
    => Check(EqualityComparer<T>.Default.Equals(a, b), $"{msg}: got {a}, want {b}");

void CheckNear(double a, double b, double eps, string msg)
    => Check(Math.Abs(a - b) < eps, $"{msg}: got {a}, want ~{b}");

float F32FromBits(uint b) => BitConverter.ToSingle(BitConverter.GetBytes(b), 0);
double F64FromBits(ulong b) => BitConverter.ToDouble(BitConverter.GetBytes(b), 0);
uint F32ToBits(float f) => BitConverter.ToUInt32(BitConverter.GetBytes(f), 0);
ulong F64ToBits(double f) => BitConverter.ToUInt64(BitConverter.GetBytes(f), 0);

// bytes field types vary by -memcpy: byte[] vs Memory<byte> vs
// ReadOnlyMemory<byte>. Reflection keeps the same generated driver valid for
// every matrix variant, including nested structs and arrays of bytes.
object BoxBytes(Type type, byte[] data) {
    if (type == typeof(byte[])) return data;
    if (type == typeof(Memory<byte>)) return new Memory<byte>(data);
    if (type == typeof(ReadOnlyMemory<byte>)) return new ReadOnlyMemory<byte>(data);
    throw new InvalidOperationException($"Unsupported bytes type: {type}");
}

byte[] UnboxBytes(object? v, Type type) {
    if (v is byte[] arr) return arr;
    if (v is Memory<byte> mem) return mem.ToArray();
    if (v is ReadOnlyMemory<byte> rm) return rm.ToArray();
    throw new InvalidOperationException($"Unsupported bytes value for {type}");
}

void SetBytesProperty(object msg, string propertyName, byte[] data) {
    var prop = msg.GetType().GetProperty(propertyName);
    if (prop == null) throw new InvalidOperationException($"{msg.GetType().Name}.{propertyName} not found");
    prop.SetValue(msg, BoxBytes(prop.PropertyType, data));
}

byte[] GetBytesProperty(object msg, string propertyName) {
    var prop = msg.GetType().GetProperty(propertyName);
    if (prop == null) throw new InvalidOperationException($"{msg.GetType().Name}.{propertyName} not found");
    return UnboxBytes(prop.GetValue(msg), prop.PropertyType);
}

void SetBytesArrayProperty(object msg, string propertyName, byte[][] values) {
    var prop = msg.GetType().GetProperty(propertyName);
    if (prop == null) throw new InvalidOperationException($"{msg.GetType().Name}.{propertyName} not found");
    var elementType = prop.PropertyType.GetElementType();
    if (elementType == null) throw new InvalidOperationException($"{prop.PropertyType} is not an array");
    var array = Array.CreateInstance(elementType, values.Length);
    for (int i = 0; i < values.Length; i++) array.SetValue(BoxBytes(elementType, values[i]), i);
    prop.SetValue(msg, array);
}

byte[] GetBytesArrayElement(object msg, string propertyName, int index) {
    var prop = msg.GetType().GetProperty(propertyName);
    if (prop == null) throw new InvalidOperationException($"{msg.GetType().Name}.{propertyName} not found");
    var array = (Array?)prop.GetValue(msg);
    var elementType = prop.PropertyType.GetElementType();
    if (array == null || elementType == null) throw new InvalidOperationException($"{propertyName} is not a bytes array");
    return UnboxBytes(array.GetValue(index), elementType);
}

int DecodeSizeDynamic(object msg, byte[] data, int start = 0) {
    var t = msg.GetType();
    var m2 = t.GetMethod("DecodeSize", new[] { typeof(byte[]), typeof(int) });
    if (m2 != null) { return (int)m2.Invoke(msg, new object[] { data, start })!; }
    var m1 = t.GetMethod("DecodeSize", new[] { typeof(byte[]) });
    if (m1 != null) {
        byte[] sliced = start == 0 ? data : data.Skip(start).ToArray();
        return (int)m1.Invoke(msg, new object[] { sliced })!;
    }
    throw new InvalidOperationException("DynamicFields.DecodeSize not found");
}

Console.WriteLine("=== Bubbler E2E Test - C# ===\n");

`)

    for _, sc := range spec.Scenarios {
        sb.WriteString(emitCs_scenario(sc))
        sb.WriteString("\n")
    }

    sb.WriteString("Console.WriteLine($\"\\n=== Results: {pass} passed, {fail} failed ===\");\n")
    sb.WriteString("Environment.Exit(fail > 0 ? 1 : 0);\n")

    return sb.String()
}

func emitCs_scenario(sc Scenario) string {
    if sc.StructName == "GetterSetter" {
        return emitCs_getterSetter(sc)
    }
    var sb strings.Builder
    fmt.Fprintf(&sb, "// %s — %s\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, "{\n    current = \"%s\";\n", sc.StructName)

    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "    /* case: %s */\n", c.Name)
        sb.WriteString("    {\n")
        fmt.Fprintf(&sb, "        var s = new %s();\n", csQual(sc))
        for _, fv := range c.Setup {
            sb.WriteString(emitCs_setField(sc, "s", fv, "        "))
        }
        sb.WriteString("        byte[] buf = s.Encode();\n")
        if !sc.IsDynamic {
            fmt.Fprintf(&sb, "        Check(buf.Length == %s.Size, \"encode length\");\n", csQual(sc))
        }
        if len(c.Wire) > 0 {
            fmt.Fprintf(&sb, "        Check(buf.SequenceEqual(new byte[]{%s}), \"golden wire\");\n",
                csByteList(c.Wire))
        }
        if sc.StructName == "BigEndianFields" {
            sb.WriteString("        CheckEq(buf[0], (byte)0xBE, \"buf[0]=0xBE\");\n")
            sb.WriteString("        CheckEq(buf[1], (byte)0x12, \"buf[1]=0x12\");\n")
            sb.WriteString("        CheckEq(buf[2], (byte)0x34, \"buf[2]=0x34\");\n")
        }
        if sc.StructName == "ConstantFields" {
            sb.WriteString("        CheckEq(buf[0], (byte)0xAA, \"header\");\n")
            sb.WriteString("        CheckEq(buf[1], (byte)0x02, \"version\");\n")
            sb.WriteString("        CheckEq(buf[4], (byte)0x02, \"magic_color\");\n")
        }

        fmt.Fprintf(&sb, "        var d = new %s();\n", csQual(sc))
        if sc.IsDynamic {
            sb.WriteString("        int n = d.Decode(buf);\n")
            sb.WriteString("        Check(n > 0, \"decode > 0\");\n")
        } else {
            fmt.Fprintf(&sb, "        Check(d.Decode(buf) == %s.Size, \"decode size\");\n", csQual(sc))
        }
        for _, af := range c.resolveAssert() {
            sb.WriteString(emitCs_assertField(sc, "d", af, "        "))
        }
        fmt.Fprintf(&sb, "        var truncated = new %s();\n", csQual(sc))
        sb.WriteString("        Check(truncated.Decode(buf.Take(buf.Length - 1).ToArray()) < 0, \"truncated decode rejected\");\n")
        for _, e := range c.Errors {
            fmt.Fprintf(&sb, "        /* decode-error: %s */\n", e.Name)
            sb.WriteString("        {\n")
            sb.WriteString("            byte[] bad = (byte[])buf.Clone();\n")
            for _, p := range e.Patches {
                fmt.Fprintf(&sb, "            bad[%d] = (byte)0x%02X;\n", p.Offset, p.Value)
            }
            fmt.Fprintf(&sb, "            var err = new %s();\n", csQual(sc))
            fmt.Fprintf(&sb, "            CheckEq(err.Decode(bad), %d, \"%s\");\n", e.ExpectedRet, e.Name)
            sb.WriteString("        }\n")
        }
        sb.WriteString("    }\n")
    }

    if len(sc.DecodeSizeChecks) > 0 {
        sb.WriteString(emitCs_decodeSize(sc))
    }
    sb.WriteString("}\n")
    return sb.String()
}

func csQual(sc Scenario) string {
    return sc.StructName // namespaces imported via using directives
}

func emitCs_setField(sc Scenario, target string, fv FieldVal, indent string) string {
    return emitCs_setNamed(sc, target, fv.Name, fv.V, indent)
}

func emitCs_setNamed(sc Scenario, target, name string, v Val, indent string) string {
    prop := pascalCase(name)

    switch v.Kind {
    case VKBool:
        return fmt.Sprintf("%s%s.%s = %s;\n", indent, target, prop, csBool(v))
    case VKU8:
        return fmt.Sprintf("%s%s.%s = (byte)%d;\n", indent, target, prop, uint8(v.U))
    case VKU16:
        return fmt.Sprintf("%s%s.%s = (ushort)%d;\n", indent, target, prop, uint16(v.U))
    case VKU32:
        return fmt.Sprintf("%s%s.%s = 0x%XU;\n", indent, target, prop, uint32(v.U))
    case VKU64:
        return fmt.Sprintf("%s%s.%s = 0x%XUL;\n", indent, target, prop, v.U)
    case VKI8:
        return fmt.Sprintf("%s%s.%s = (sbyte)%d;\n", indent, target, prop, int8(v.I))
    case VKI16:
        return fmt.Sprintf("%s%s.%s = (short)%d;\n", indent, target, prop, int16(v.I))
    case VKI32:
        return fmt.Sprintf("%s%s.%s = %d;\n", indent, target, prop, int32(v.I))
    case VKI64:
        return fmt.Sprintf("%s%s.%s = %dL;\n", indent, target, prop, v.I)
    case VKF32:
        return fmt.Sprintf("%s%s.%s = F32FromBits(0x%08XU);\n", indent, target, prop, uint32(v.U))
    case VKF64:
        return fmt.Sprintf("%s%s.%s = F64FromBits(0x%016XUL);\n", indent, target, prop, v.U)
    case VKEnum:
        return fmt.Sprintf("%s%s.%s = %s.%s;\n", indent, target, prop, v.EnumType, v.EnumName)
    case VKString:
        return fmt.Sprintf("%s%s.%s = %s;\n", indent, target, prop, csStringLit(v.Str))
    case VKBytes:
        if len(v.Bytes) == 0 {
            return fmt.Sprintf("%sSetBytesProperty(%s, \"%s\", new byte[0]);\n", indent, target, prop)
        }
        return fmt.Sprintf("%sSetBytesProperty(%s, \"%s\", new byte[]{%s});\n",
            indent, target, prop, csByteList(v.Bytes))
    case VKStruct:
        var sb strings.Builder
        tmp := csTempName(target + "_" + name)
        fmt.Fprintf(&sb, "%svar %s = new %s();\n", indent, tmp, v.Struct.Type)
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitCs_setNamed(sc, tmp, f.Name, f.V, indent))
        }
        fmt.Fprintf(&sb, "%s%s.%s = %s;\n", indent, target, prop, tmp)
        return sb.String()
    case VKArray:
        return emitCs_setArray(sc, target, prop, v, indent)
    }
    return ""
}

func emitCs_setArray(sc Scenario, target, prop string, v Val, indent string) string {
    elemKind := v.Array.ElemKind
    var sb strings.Builder
    if elemKind == VKBytes {
        values := make([]string, len(v.Array.Items))
        for i, item := range v.Array.Items {
            if len(item.Bytes) == 0 {
                values[i] = "new byte[0]"
            } else {
                values[i] = fmt.Sprintf("new byte[]{%s}", csByteList(item.Bytes))
            }
        }
        fmt.Fprintf(&sb, "%sSetBytesArrayProperty(%s, \"%s\", new byte[][]{%s});\n",
            indent, target, prop, strings.Join(values, ", "))
        return sb.String()
    }
    // For arrays of struct: build each element via temp variable.
    if elemKind == VKStruct {
        tmp := csTempName(target + "_" + prop)
        fmt.Fprintf(&sb, "%svar %s = new %s[%d];\n", indent, tmp, v.Array.ElemType, len(v.Array.Items))
        for i, item := range v.Array.Items {
            etmp := csTempName(fmt.Sprintf("%s_%d", tmp, i))
            fmt.Fprintf(&sb, "%svar %s = new %s();\n", indent, etmp, item.Struct.Type)
            for _, f := range item.Struct.Fields {
                sb.WriteString(emitCs_setNamed(sc, etmp, f.Name, f.V, indent))
            }
            fmt.Fprintf(&sb, "%s%s[%d] = %s;\n", indent, tmp, i, etmp)
        }
        fmt.Fprintf(&sb, "%s%s.%s = %s;\n", indent, target, prop, tmp)
        return sb.String()
    }

    // For other array kinds: emit a single new <T>[] { ... } literal.
    items := make([]string, len(v.Array.Items))
    for i, it := range v.Array.Items {
        items[i] = csValueExpr(it)
    }
    var elemType string
    switch elemKind {
    case VKU8:
        elemType = "byte"
    case VKU16:
        elemType = "ushort"
    case VKU32:
        elemType = "uint"
    case VKU64:
        elemType = "ulong"
    case VKI8:
        elemType = "sbyte"
    case VKI16:
        elemType = "short"
    case VKI32:
        elemType = "int"
    case VKI64:
        elemType = "long"
    case VKF32:
        elemType = "float"
    case VKF64:
        elemType = "double"
    case VKEnum:
        elemType = v.Array.ElemType
    case VKBool:
        elemType = "bool"
    case VKString:
        elemType = "string"
    }
    fmt.Fprintf(&sb, "%s%s.%s = new %s[]{%s};\n", indent, target, prop, elemType, strings.Join(items, ", "))
    return sb.String()
}

func emitCs_assertField(sc Scenario, target string, af AssertField, indent string) string {
    return emitCs_assertNamed(sc, target, af.Name, af.V, af.Tol, indent)
}

func emitCs_assertNamed(sc Scenario, target, name string, v Val, tol float64, indent string) string {
    prop := pascalCase(name)
    msg := name

    if v.Kind == VKBytes {
        if len(v.Bytes) == 0 {
            return fmt.Sprintf("%sCheck(GetBytesProperty(%s, \"%s\").Length == 0, \"%s empty\");\n",
                indent, target, prop, msg)
        }
        return fmt.Sprintf("%sCheck(GetBytesProperty(%s, \"%s\").SequenceEqual(new byte[]{%s}), \"%s\");\n",
            indent, target, prop, csByteList(v.Bytes), msg)
    }

    switch v.Kind {
    case VKBool:
        return fmt.Sprintf("%sCheckEq(%s.%s, %s, \"%s\");\n", indent, target, prop, csBool(v), msg)
    case VKU8:
        return fmt.Sprintf("%sCheckEq(%s.%s, (byte)%d, \"%s\");\n", indent, target, prop, uint8(v.U), msg)
    case VKU16:
        return fmt.Sprintf("%sCheckEq(%s.%s, (ushort)%d, \"%s\");\n", indent, target, prop, uint16(v.U), msg)
    case VKU32:
        return fmt.Sprintf("%sCheckEq(%s.%s, 0x%XU, \"%s\");\n", indent, target, prop, uint32(v.U), msg)
    case VKU64:
        return fmt.Sprintf("%sCheckEq(%s.%s, 0x%XUL, \"%s\");\n", indent, target, prop, v.U, msg)
    case VKI8:
        return fmt.Sprintf("%sCheckEq(%s.%s, (sbyte)%d, \"%s\");\n", indent, target, prop, int8(v.I), msg)
    case VKI16:
        return fmt.Sprintf("%sCheckEq(%s.%s, (short)%d, \"%s\");\n", indent, target, prop, int16(v.I), msg)
    case VKI32:
        return fmt.Sprintf("%sCheckEq(%s.%s, %d, \"%s\");\n", indent, target, prop, int32(v.I), msg)
    case VKI64:
        return fmt.Sprintf("%sCheckEq(%s.%s, %dL, \"%s\");\n", indent, target, prop, v.I, msg)
    case VKF32:
        if tol > 0 {
            return fmt.Sprintf("%sCheckNear(%s.%s, F32FromBits(0x%08XU), %g, \"%s\");\n",
                indent, target, prop, uint32(v.U), tol, msg)
        }
        return fmt.Sprintf("%sCheckEq(F32ToBits(%s.%s), 0x%08XU, \"%s bits\");\n",
            indent, target, prop, uint32(v.U), msg)
    case VKF64:
        if tol > 0 {
            return fmt.Sprintf("%sCheckNear(%s.%s, F64FromBits(0x%016XUL), %g, \"%s\");\n",
                indent, target, prop, v.U, tol, msg)
        }
        return fmt.Sprintf("%sCheckEq(F64ToBits(%s.%s), 0x%016XUL, \"%s bits\");\n",
            indent, target, prop, v.U, msg)
    case VKEnum:
        return fmt.Sprintf("%sCheckEq(%s.%s, %s.%s, \"%s\");\n",
            indent, target, prop, v.EnumType, v.EnumName, msg)
    case VKString:
        return fmt.Sprintf("%sCheckEq(%s.%s, %s, \"%s\");\n",
            indent, target, prop, csStringLit(v.Str), msg)
    case VKBytes:
        if len(v.Bytes) == 0 {
            return fmt.Sprintf("%sCheck(%s.%s.Length == 0, \"%s empty\");\n", indent, target, prop, msg)
        }
        return fmt.Sprintf("%sCheck(%s.%s.SequenceEqual(new byte[]{%s}), \"%s\");\n",
            indent, target, prop, csByteList(v.Bytes), msg)
    case VKStruct:
        var sb strings.Builder
        tmp := csTempName(target + "_g_" + name)
        fmt.Fprintf(&sb, "%svar %s = %s.%s;\n", indent, tmp, target, prop)
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitCs_assertNamed(sc, tmp, f.Name, f.V, tol, indent))
        }
        return sb.String()
    case VKArray:
        var sb strings.Builder
        for i, it := range v.Array.Items {
            label := fmt.Sprintf("%s[%d]", msg, i)
            sb.WriteString(emitCs_assertNamed_index(sc, target, prop, i, it, tol, indent, label))
        }
        return sb.String()
    }
    return ""
}

func emitCs_assertNamed_index(sc Scenario, target, prop string, i int, v Val, tol float64, indent, label string) string {
    accessor := fmt.Sprintf("%s.%s[%d]", target, prop, i)
    switch v.Kind {
    case VKBool:
        return fmt.Sprintf("%sCheckEq(%s, %s, \"%s\");\n", indent, accessor, csBool(v), label)
    case VKU8:
        return fmt.Sprintf("%sCheckEq(%s, (byte)%d, \"%s\");\n", indent, accessor, uint8(v.U), label)
    case VKU16:
        return fmt.Sprintf("%sCheckEq(%s, (ushort)%d, \"%s\");\n", indent, accessor, uint16(v.U), label)
    case VKU32:
        return fmt.Sprintf("%sCheckEq(%s, 0x%XU, \"%s\");\n", indent, accessor, uint32(v.U), label)
    case VKU64:
        return fmt.Sprintf("%sCheckEq(%s, 0x%XUL, \"%s\");\n", indent, accessor, v.U, label)
    case VKI8:
        return fmt.Sprintf("%sCheckEq(%s, (sbyte)%d, \"%s\");\n", indent, accessor, int8(v.I), label)
    case VKI16:
        return fmt.Sprintf("%sCheckEq(%s, (short)%d, \"%s\");\n", indent, accessor, int16(v.I), label)
    case VKI32:
        return fmt.Sprintf("%sCheckEq(%s, %d, \"%s\");\n", indent, accessor, int32(v.I), label)
    case VKI64:
        return fmt.Sprintf("%sCheckEq(%s, %dL, \"%s\");\n", indent, accessor, v.I, label)
    case VKF32:
        if tol > 0 {
            return fmt.Sprintf("%sCheckNear(%s, F32FromBits(0x%08XU), %g, \"%s\");\n",
                indent, accessor, uint32(v.U), tol, label)
        }
        return fmt.Sprintf("%sCheckEq(F32ToBits(%s), 0x%08XU, \"%s bits\");\n",
            indent, accessor, uint32(v.U), label)
    case VKF64:
        if tol > 0 {
            return fmt.Sprintf("%sCheckNear(%s, F64FromBits(0x%016XUL), %g, \"%s\");\n",
                indent, accessor, v.U, tol, label)
        }
        return fmt.Sprintf("%sCheckEq(F64ToBits(%s), 0x%016XUL, \"%s bits\");\n",
            indent, accessor, v.U, label)
    case VKEnum:
        return fmt.Sprintf("%sCheckEq(%s, %s.%s, \"%s\");\n", indent, accessor, v.EnumType, v.EnumName, label)
    case VKString:
        return fmt.Sprintf("%sCheckEq(%s, %s, \"%s\");\n", indent, accessor, csStringLit(v.Str), label)
    case VKBytes:
        if len(v.Bytes) == 0 {
            return fmt.Sprintf("%sCheck(GetBytesArrayElement(%s, \"%s\", %d).Length == 0, \"%s empty\");\n",
                indent, target, prop, i, label)
        }
        return fmt.Sprintf("%sCheck(GetBytesArrayElement(%s, \"%s\", %d).SequenceEqual(new byte[]{%s}), \"%s\");\n",
            indent, target, prop, i, csByteList(v.Bytes), label)
    case VKStruct:
        var sb strings.Builder
        tmp := csTempName(fmt.Sprintf("%s_%s_%d", target, prop, i))
        fmt.Fprintf(&sb, "%svar %s = %s.%s[%d];\n", indent, tmp, target, prop, i)
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitCs_assertNamed(sc, tmp, f.Name, f.V, tol, indent))
        }
        return sb.String()
    }
    return ""
}

func emitCs_decodeSize(sc Scenario) string {
    var sb strings.Builder
    sb.WriteString("    /* --- decode_size boundary checks --- */\n")
    sb.WriteString("    {\n")

    var needSource bool
    var srcCase string
    for _, ds := range sc.DecodeSizeChecks {
        if ds.SourceCase != "" {
            needSource = true
            srcCase = ds.SourceCase
        }
    }
    if needSource {
        var c Case
        for _, cc := range sc.Cases {
            if cc.Name == srcCase {
                c = cc
                break
            }
        }
        fmt.Fprintf(&sb, "        var src = new %s();\n", sc.StructName)
        for _, fv := range c.Setup {
            sb.WriteString(emitCs_setNamed(sc, "src", fv.Name, fv.V, "        "))
        }
        sb.WriteString("        byte[] full = src.Encode();\n")
    }
    fmt.Fprintf(&sb, "        var probe = new %s();\n", sc.StructName)
    for _, ds := range sc.DecodeSizeChecks {
        fmt.Fprintf(&sb, "        /* %s */\n", ds.Name)
        if ds.SourceCase != "" {
            if ds.Truncate == 0 {
                sb.WriteString("        CheckEq(DecodeSizeDynamic(probe, full), full.Length, \"complete\");\n")
            } else {
                fmt.Fprintf(&sb, "        CheckEq(DecodeSizeDynamic(probe, full.Take(full.Length - %d).ToArray()), -full.Length, \"truncate %d\");\n",
                    ds.Truncate, ds.Truncate)
            }
        } else {
            fmt.Fprintf(&sb, "        CheckEq(DecodeSizeDynamic(probe, new byte[]{%s}), %d, \"%s\");\n",
                csByteList(ds.Bytes), ds.Expected, ds.Name)
        }
    }
    sb.WriteString("    }\n")
    return sb.String()
}

func emitCs_getterSetter(sc Scenario) string {
    var sb strings.Builder
    fmt.Fprintf(&sb, "// %s — %s\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, "{\n    current = \"%s\";\n", sc.StructName)
    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "    /* case: %s */\n", c.Name)
        sb.WriteString("    {\n")
        fmt.Fprintf(&sb, "        var s = new %s();\n", sc.StructName)
        for _, ap := range c.Accessors {
            fmt.Fprintf(&sb, "        s.%s = F64FromBits(0x%016XUL);\n", pascalCase(ap.SetterName), ap.SetArg.U)
        }
        roundTrip := false
        for _, ap := range c.Accessors {
            if !ap.NoRoundTrip {
                roundTrip = true
                break
            }
        }
        if roundTrip {
            sb.WriteString("        byte[] buf = s.Encode();\n")
            fmt.Fprintf(&sb, "        var d = new %s();\n", sc.StructName)
            fmt.Fprintf(&sb, "        Check(d.Decode(buf) == %s.Size, \"decode size\");\n", sc.StructName)
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "        CheckNear(d.%s, F64FromBits(0x%016XUL), %g, \"%s\");\n",
                    pascalCase(ap.GetterName), ap.Expected.U, tol, ap.GetterName)
            }
        } else {
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "        CheckNear(s.%s, F64FromBits(0x%016XUL), %g, \"%s\");\n",
                    pascalCase(ap.GetterName), ap.Expected.U, tol, ap.GetterName)
            }
        }
        sb.WriteString("    }\n")
    }
    sb.WriteString("}\n")
    return sb.String()
}

// ──────────────────────────────────────────────────────────────────────────
// Value formatting
// ──────────────────────────────────────────────────────────────────────────

func csBool(v Val) string {
    if v.U != 0 {
        return "true"
    }
    return "false"
}

func csValueExpr(v Val) string {
    switch v.Kind {
    case VKBool:
        return csBool(v)
    case VKU8:
        return fmt.Sprintf("(byte)%d", uint8(v.U))
    case VKU16:
        return fmt.Sprintf("(ushort)%d", uint16(v.U))
    case VKU32:
        return fmt.Sprintf("0x%XU", uint32(v.U))
    case VKU64:
        return fmt.Sprintf("0x%XUL", v.U)
    case VKI8:
        return fmt.Sprintf("(sbyte)%d", int8(v.I))
    case VKI16:
        return fmt.Sprintf("(short)%d", int16(v.I))
    case VKI32:
        return fmt.Sprintf("%d", int32(v.I))
    case VKI64:
        return fmt.Sprintf("%dL", v.I)
    case VKF32:
        return fmt.Sprintf("F32FromBits(0x%08XU)", uint32(v.U))
    case VKF64:
        return fmt.Sprintf("F64FromBits(0x%016XUL)", v.U)
    case VKEnum:
        return fmt.Sprintf("%s.%s", v.EnumType, v.EnumName)
    case VKString:
        return csStringLit(v.Str)
    }
    return ""
}

func csStringLit(s string) string {
    var sb strings.Builder
    sb.WriteByte('"')
    for _, r := range s {
        switch r {
        case '\\':
            sb.WriteString("\\\\")
        case '"':
            sb.WriteString("\\\"")
        case '\n':
            sb.WriteString("\\n")
        case '\r':
            sb.WriteString("\\r")
        case '\t':
            sb.WriteString("\\t")
        default:
            if r < 0x20 || r > 0x7E {
                if r > 0xFFFF {
                    fmt.Fprintf(&sb, "\\U%08x", r)
                } else {
                    fmt.Fprintf(&sb, "\\u%04x", r)
                }
            } else {
                sb.WriteRune(r)
            }
        }
    }
    sb.WriteByte('"')
    return sb.String()
}

func csByteList(b []byte) string {
    parts := make([]string, len(b))
    for i, v := range b {
        parts[i] = fmt.Sprintf("0x%02X", v)
    }
    return strings.Join(parts, ", ")
}

func csTempName(s string) string {
    var sb strings.Builder
    sb.WriteByte('_')
    for _, r := range s {
        if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
            sb.WriteRune(r)
        } else {
            sb.WriteByte('_')
        }
    }
    return sb.String()
}
