package main

import (
    "fmt"
    "strings"
)

// EmitPython produces e2e/tests/python/test_main.py from the spec.
func EmitPython(spec *Spec) string {
    var sb strings.Builder

    sb.WriteString(`"""
Bubbler E2E Test - Python target

GENERATED by e2e/spec; DO NOT EDIT BY HAND.
Source of truth: e2e/spec/scenarios.go

Run (after code-gen):
  python3 test_main.py
"""
import sys
import math
import struct
import unittest
sys.path.insert(0, "gen")

from testcase_bb import (
    Color, Status,
    Point,
    SimpleScalars,
    BitPacked,
    BigEndianFields,
    ArrayFields,
    EmbedStructs,
    ConstantFields,
    GetterSetter,
    DynamicFields,
    FloatSpecials,
    SmallArrays,
    MediumArrays,
    LargeArrays,
    VeryLargeArrays,
    MixedArrays,
    BlobRecord,
    CodecArrays,
)
from bitwid_bb import NarrowBWTest


def f32_from_bits(b):
    return struct.unpack('<f', struct.pack('<I', b & 0xFFFFFFFF))[0]


def f64_from_bits(b):
    return struct.unpack('<d', struct.pack('<Q', b & 0xFFFFFFFFFFFFFFFF))[0]


def f32_to_bits(f):
    return struct.unpack('<I', struct.pack('<f', f))[0]


def f64_to_bits(f):
    return struct.unpack('<Q', struct.pack('<d', f))[0]


`)

    for _, sc := range spec.Scenarios {
        sb.WriteString(emitPy_scenario(sc))
        sb.WriteString("\n")
    }

    sb.WriteString(`
if __name__ == "__main__":
    result = unittest.main(verbosity=2, exit=False)
    sys.exit(0 if result.result.wasSuccessful() else 1)
`)
    return sb.String()
}

func emitPy_scenario(sc Scenario) string {
    if sc.StructName == "GetterSetter" {
        return emitPy_getterSetter(sc)
    }
    var sb strings.Builder
    fmt.Fprintf(&sb, "class Test%s(unittest.TestCase):\n", sc.StructName)
    fmt.Fprintf(&sb, "    \"\"\"%s\"\"\"\n", sc.Notes)

    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "    def test_%s(self):\n", c.Name)
        fmt.Fprintf(&sb, "        s = %s()\n", sc.StructName)
        for _, fv := range c.Setup {
            sb.WriteString(emitPy_assignVal("s."+fv.Name, fv.V, "        "))
        }
        sb.WriteString("        buf = s.encode()\n")
        if !sc.IsDynamic {
            fmt.Fprintf(&sb, "        self.assertEqual(len(buf), %s.size(), \"encode size\")\n", sc.StructName)
        }
        if len(c.Wire) > 0 {
            fmt.Fprintf(&sb, "        self.assertEqual(bytes(buf), bytes([%s]), \"golden wire\")\n",
                pyByteList(c.Wire))
        }
        if sc.StructName == "BigEndianFields" {
            sb.WriteString("        self.assertEqual(buf[0], 0xBE)\n")
            sb.WriteString("        self.assertEqual(buf[1], 0x12)\n")
            sb.WriteString("        self.assertEqual(buf[2], 0x34)\n")
        }
        if sc.StructName == "ConstantFields" {
            sb.WriteString("        self.assertEqual(buf[0], 0xAA)\n")
            sb.WriteString("        self.assertEqual(buf[1], 0x02)\n")
            sb.WriteString("        self.assertEqual(buf[4], 0x02)\n")
        }
        fmt.Fprintf(&sb, "        d = %s()\n", sc.StructName)
        sb.WriteString("        ok, n = d.decode(buf)\n")
        sb.WriteString("        self.assertTrue(ok, \"decode ok\")\n")
        if !sc.IsDynamic {
            fmt.Fprintf(&sb, "        self.assertEqual(n, %s.size(), \"decode size\")\n", sc.StructName)
        }
        for _, af := range c.resolveAssert() {
            sb.WriteString(emitPy_assertVal("d."+af.Name, af.V, af.Tol, "        "))
        }
        fmt.Fprintf(&sb, "        truncated = %s()\n", sc.StructName)
        sb.WriteString("        truncated_ok, _ = truncated.decode(bytes(buf[:-1]))\n")
        sb.WriteString("        self.assertFalse(truncated_ok, \"truncated decode rejected\")\n")
        for _, e := range c.Errors {
            fmt.Fprintf(&sb, "        # decode-error: %s\n", e.Name)
            sb.WriteString("        bad = bytearray(buf)\n")
            for _, p := range e.Patches {
                fmt.Fprintf(&sb, "        bad[%d] = 0x%02X\n", p.Offset, p.Value)
            }
            fmt.Fprintf(&sb, "        err = %s()\n", sc.StructName)
            sb.WriteString("        ok, _ = err.decode(bytes(bad))\n")
            sb.WriteString("        self.assertFalse(ok)\n")
        }
    }

    if len(sc.DecodeSizeChecks) > 0 {
        sb.WriteString(emitPy_decodeSize(sc))
    }
    return sb.String()
}

func emitPy_assignVal(dst string, v Val, indent string) string {
    switch v.Kind {
    case VKBool:
        if v.U != 0 {
            return fmt.Sprintf("%s%s = True\n", indent, dst)
        }
        return fmt.Sprintf("%s%s = False\n", indent, dst)
    case VKU8, VKU16, VKU32, VKU64:
        return fmt.Sprintf("%s%s = 0x%X\n", indent, dst, v.U)
    case VKI8, VKI16, VKI32, VKI64:
        return fmt.Sprintf("%s%s = %d\n", indent, dst, v.I)
    case VKF32:
        return fmt.Sprintf("%s%s = f32_from_bits(0x%08X)\n", indent, dst, uint32(v.U))
    case VKF64:
        return fmt.Sprintf("%s%s = f64_from_bits(0x%016X)\n", indent, dst, v.U)
    case VKEnum:
        return fmt.Sprintf("%s%s = %s.%s\n", indent, dst, v.EnumType, v.EnumName)
    case VKString:
        return fmt.Sprintf("%s%s = %s\n", indent, dst, pyStringLit(v.Str))
    case VKBytes:
        if len(v.Bytes) == 0 {
            return fmt.Sprintf("%s%s = b\"\"\n", indent, dst)
        }
        return fmt.Sprintf("%s%s = bytes([%s])\n", indent, dst, pyByteList(v.Bytes))
    case VKStruct:
        // Build a Point() instance, set fields, then assign to dst.
        var sb strings.Builder
        // We use a temp variable derived from the destination to avoid clashes.
        tmp := pyTempName(dst)
        fmt.Fprintf(&sb, "%s%s = %s()\n", indent, tmp, v.Struct.Type)
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitPy_assignVal(tmp+"."+f.Name, f.V, indent))
        }
        fmt.Fprintf(&sb, "%s%s = %s\n", indent, dst, tmp)
        return sb.String()
    case VKArray:
        // Element kind dictates how we build the list.
        var items []string
        var sb strings.Builder
        for i, item := range v.Array.Items {
            if item.Kind == VKStruct {
                tmp := pyTempName(fmt.Sprintf("%s_%d", dst, i))
                fmt.Fprintf(&sb, "%s%s = %s()\n", indent, tmp, item.Struct.Type)
                for _, f := range item.Struct.Fields {
                    sb.WriteString(emitPy_assignVal(tmp+"."+f.Name, f.V, indent))
                }
                items = append(items, tmp)
            } else {
                items = append(items, pyValueExpr(item))
            }
        }
        fmt.Fprintf(&sb, "%s%s = [%s]\n", indent, dst, strings.Join(items, ", "))
        return sb.String()
    }
    return ""
}

func emitPy_assertVal(dst string, v Val, tol float64, indent string) string {
    switch v.Kind {
    case VKBool:
        if v.U != 0 {
            return fmt.Sprintf("%sself.assertTrue(%s)\n", indent, dst)
        }
        return fmt.Sprintf("%sself.assertFalse(%s)\n", indent, dst)
    case VKU8, VKU16, VKU32, VKU64:
        return fmt.Sprintf("%sself.assertEqual(%s, 0x%X)\n", indent, dst, v.U)
    case VKI8, VKI16, VKI32, VKI64:
        return fmt.Sprintf("%sself.assertEqual(%s, %d)\n", indent, dst, v.I)
    case VKF32:
        if tol > 0 {
            return fmt.Sprintf("%sself.assertAlmostEqual(%s, f32_from_bits(0x%08X), delta=%g)\n",
                indent, dst, uint32(v.U), tol)
        }
        return fmt.Sprintf("%sself.assertEqual(f32_to_bits(%s), 0x%08X)\n",
            indent, dst, uint32(v.U))
    case VKF64:
        if tol > 0 {
            return fmt.Sprintf("%sself.assertAlmostEqual(%s, f64_from_bits(0x%016X), delta=%g)\n",
                indent, dst, v.U, tol)
        }
        return fmt.Sprintf("%sself.assertEqual(f64_to_bits(%s), 0x%016X)\n",
            indent, dst, v.U)
    case VKEnum:
        return fmt.Sprintf("%sself.assertEqual(%s, %s.%s)\n",
            indent, dst, v.EnumType, v.EnumName)
    case VKString:
        return fmt.Sprintf("%sself.assertEqual(%s, %s)\n",
            indent, dst, pyStringLit(v.Str))
    case VKBytes:
        if len(v.Bytes) == 0 {
            return fmt.Sprintf("%sself.assertEqual(len(%s), 0)\n", indent, dst)
        }
        return fmt.Sprintf("%sself.assertEqual(bytes(%s), bytes([%s]))\n",
            indent, dst, pyByteList(v.Bytes))
    case VKStruct:
        var sb strings.Builder
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitPy_assertVal(dst+"."+f.Name, f.V, tol, indent))
        }
        return sb.String()
    case VKArray:
        var sb strings.Builder
        for i, it := range v.Array.Items {
            sb.WriteString(emitPy_assertVal(fmt.Sprintf("%s[%d]", dst, i), it, tol, indent))
        }
        return sb.String()
    }
    return ""
}

func emitPy_decodeSize(sc Scenario) string {
    var sb strings.Builder
    sb.WriteString("    def test_decode_size(self):\n")

    var needSource bool
    var srcCase string
    for _, ds := range sc.DecodeSizeChecks {
        if ds.SourceCase != "" {
            needSource = true
            srcCase = ds.SourceCase
        }
    }
    if needSource {
        var c Case
        for _, cc := range sc.Cases {
            if cc.Name == srcCase {
                c = cc
                break
            }
        }
        fmt.Fprintf(&sb, "        src = %s()\n", sc.StructName)
        for _, fv := range c.Setup {
            sb.WriteString(emitPy_assignVal("src."+fv.Name, fv.V, "        "))
        }
        sb.WriteString("        full = src.encode()\n")
    }
    fmt.Fprintf(&sb, "        d = %s()\n", sc.StructName)
    for _, ds := range sc.DecodeSizeChecks {
        fmt.Fprintf(&sb, "        # %s\n", ds.Name)
        if ds.SourceCase != "" {
            if ds.Truncate == 0 {
                sb.WriteString("        self.assertEqual(d.decode_size(bytes(full)), len(full))\n")
            } else {
                fmt.Fprintf(&sb, "        self.assertEqual(d.decode_size(bytes(full[:-%d])), -len(full))\n", ds.Truncate)
            }
        } else {
            fmt.Fprintf(&sb, "        self.assertEqual(d.decode_size(bytes([%s])), %d)\n",
                pyByteList(ds.Bytes), ds.Expected)
        }
    }
    return sb.String()
}

func emitPy_getterSetter(sc Scenario) string {
    var sb strings.Builder
    fmt.Fprintf(&sb, "class Test%s(unittest.TestCase):\n", sc.StructName)
    fmt.Fprintf(&sb, "    \"\"\"%s\"\"\"\n", sc.Notes)
    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "    def test_%s(self):\n", c.Name)
        fmt.Fprintf(&sb, "        s = %s()\n", sc.StructName)
        for _, ap := range c.Accessors {
            fmt.Fprintf(&sb, "        s.%s = f64_from_bits(0x%016X)\n", ap.SetterName, ap.SetArg.U)
        }
        roundTrip := false
        for _, ap := range c.Accessors {
            if !ap.NoRoundTrip {
                roundTrip = true
                break
            }
        }
        if roundTrip {
            sb.WriteString("        buf = s.encode()\n")
            fmt.Fprintf(&sb, "        d = %s()\n", sc.StructName)
            sb.WriteString("        ok, _ = d.decode(buf)\n")
            sb.WriteString("        self.assertTrue(ok)\n")
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "        self.assertAlmostEqual(d.%s, f64_from_bits(0x%016X), delta=%g)\n",
                    ap.GetterName, ap.Expected.U, tol)
            }
        } else {
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "        self.assertAlmostEqual(s.%s, f64_from_bits(0x%016X), delta=%g)\n",
                    ap.GetterName, ap.Expected.U, tol)
            }
        }
    }
    return sb.String()
}

func pyValueExpr(v Val) string {
    switch v.Kind {
    case VKBool:
        if v.U != 0 {
            return "True"
        }
        return "False"
    case VKU8, VKU16, VKU32, VKU64:
        return fmt.Sprintf("0x%X", v.U)
    case VKI8, VKI16, VKI32, VKI64:
        return fmt.Sprintf("%d", v.I)
    case VKF32:
        return fmt.Sprintf("f32_from_bits(0x%08X)", uint32(v.U))
    case VKF64:
        return fmt.Sprintf("f64_from_bits(0x%016X)", v.U)
    case VKEnum:
        return fmt.Sprintf("%s.%s", v.EnumType, v.EnumName)
    case VKString:
        return pyStringLit(v.Str)
    case VKBytes:
        if len(v.Bytes) == 0 {
            return "b\"\""
        }
        return fmt.Sprintf("bytes([%s])", pyByteList(v.Bytes))
    }
    return ""
}

func pyStringLit(s string) string {
    var sb strings.Builder
    sb.WriteByte('"')
    for _, r := range s {
        switch r {
        case '\\':
            sb.WriteString("\\\\")
        case '"':
            sb.WriteString("\\\"")
        case '\n':
            sb.WriteString("\\n")
        case '\r':
            sb.WriteString("\\r")
        case '\t':
            sb.WriteString("\\t")
        default:
            if r < 0x20 || r > 0x7E {
                if r > 0xFFFF {
                    fmt.Fprintf(&sb, "\\U%08x", r)
                } else {
                    fmt.Fprintf(&sb, "\\u%04x", r)
                }
            } else {
                sb.WriteRune(r)
            }
        }
    }
    sb.WriteByte('"')
    return sb.String()
}

func pyByteList(b []byte) string {
    parts := make([]string, len(b))
    for i, v := range b {
        parts[i] = fmt.Sprintf("0x%02X", v)
    }
    return strings.Join(parts, ", ")
}

// pyTempName derives a sanitised temp variable name from a target lvalue.
// e.g. "s.point_arr_0" → "_t_s_point_arr_0".
func pyTempName(dst string) string {
    var sb strings.Builder
    sb.WriteString("_t_")
    for _, r := range dst {
        if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
            sb.WriteRune(r)
        } else {
            sb.WriteByte('_')
        }
    }
    return sb.String()
}
