package main

import (
    "fmt"
    "strings"
)

// EmitCjs and EmitEsm share the bulk of their structure — both are JS
// scripts in .mjs that import the generated package, then run cases. They
// only differ in how the package is imported.

func EmitCjs(spec *Spec) string {
    return emitJS(spec, jsModeCjs)
}

func EmitEsm(spec *Spec) string {
    return emitJS(spec, jsModeEsm)
}

type jsMode int

const (
    jsModeCjs jsMode = iota
    jsModeEsm
)

func emitJS(spec *Spec, mode jsMode) string {
    var sb strings.Builder

    label := "CommonJS"
    if mode == jsModeEsm {
        label = "ESModule"
    }

    fmt.Fprintf(&sb, `/**
 * Bubbler E2E Test - %s target
 *
 * GENERATED by e2e/spec; DO NOT EDIT BY HAND.
 * Source of truth: e2e/spec/scenarios.go
 */
`, label)

    if mode == jsModeCjs {
        sb.WriteString(`import { createRequire } from "module";
const require = createRequire(import.meta.url);
const pkg = require("./gen/testcase.bb.js").testpkg;
const bw  = require("./gen/bitwid.bb.js").bitwid;
`)
    } else {
        sb.WriteString(`import pkgRoot from "./gen/testcase.bb.js";
import bwRoot  from "./gen/bitwid.bb.js";
const pkg = pkgRoot.testpkg;
const bw  = bwRoot.bitwid;
`)
    }

    sb.WriteString(`
let g_pass = 0, g_fail = 0, g_current = "";
function check(cond, msg) {
    if (cond) { g_pass++; }
    else { process.stderr.write(` + "`  FAIL [${g_current}] ${msg}\\n`" + `); g_fail++; }
}
function checkEq(a, b, msg) {
    check(a === b, ` + "`${msg}: got ${a}, want ${b}`" + `);
}
function checkBig(a, b, msg) {
    check(BigInt(a) === BigInt(b), ` + "`${msg}: got ${a}, want ${b}`" + `);
}
function checkNear(a, b, eps, msg) {
    check(Math.abs(Number(a) - Number(b)) < eps, ` + "`${msg}: got ${a}, want ~${b}`" + `);
}

// Bit-pattern float helpers — used for IEEE-754 corner-case round-trips.
const _f32buf = new ArrayBuffer(4);
const _f32u = new Uint32Array(_f32buf);
const _f32f = new Float32Array(_f32buf);
function f32FromBits(b) { _f32u[0] = (b >>> 0); return _f32f[0]; }
function f32ToBits(f) { _f32f[0] = f; return _f32u[0]; }

const _f64buf = new ArrayBuffer(8);
const _f64u = new BigUint64Array(_f64buf);
const _f64f = new Float64Array(_f64buf);
function f64FromBits(b) { _f64u[0] = BigInt(b); return _f64f[0]; }
function f64ToBits(f) { _f64f[0] = f; return _f64u[0]; }

function decodeSizeDynamic(data, start = 0) {
    if (typeof pkg.DynamicFields.decode_size === "function") {
        return pkg.DynamicFields.decode_size(data, start);
    }
    const inst = new pkg.DynamicFields();
    if (typeof inst.decode_size === "function") {
        return inst.decode_size(data, start);
    }
    throw new Error("DynamicFields decode_size is not available");
}

`)

    for _, sc := range spec.Scenarios {
        sb.WriteString(emitJS_scenario(sc))
        sb.WriteString("\n")
    }

    sb.WriteString(fmt.Sprintf("\nconsole.log(`\\n=== Bubbler E2E Test - %s ===`);\n", label))
    sb.WriteString("console.log(`=== Results: ${g_pass} passed, ${g_fail} failed ===`);\n")
    sb.WriteString("process.exit(g_fail > 0 ? 1 : 0);\n")
    return sb.String()
}

func emitJS_scenario(sc Scenario) string {
    if sc.StructName == "GetterSetter" {
        return emitJS_getterSetter(sc)
    }
    var sb strings.Builder
    fmt.Fprintf(&sb, "// %s — %s\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, "g_current = \"%s\";\n", sc.StructName)

    nsPrefix := jsNS(sc)

    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "// case: %s\n", c.Name)
        sb.WriteString("{\n")
        fmt.Fprintf(&sb, "    const s = new %s.%s();\n", nsPrefix, sc.StructName)
        for _, fv := range c.Setup {
            sb.WriteString(emitJS_setField("s", fv, "    ", nsPrefix))
        }
        fmt.Fprintf(&sb, "    const buf = %s.%s.encode(s);\n", nsPrefix, sc.StructName)
        if !sc.IsDynamic {
            fmt.Fprintf(&sb, "    check(buf.length === %s.%s.size(), \"encode length\");\n", nsPrefix, sc.StructName)
        }
        if sc.StructName == "BigEndianFields" {
            sb.WriteString("    checkEq(buf[0], 0xBE, \"buf[0]=0xBE\");\n")
            sb.WriteString("    checkEq(buf[1], 0x12, \"buf[1]=0x12\");\n")
            sb.WriteString("    checkEq(buf[2], 0x34, \"buf[2]=0x34\");\n")
        }
        if sc.StructName == "ConstantFields" {
            sb.WriteString("    checkEq(buf[0], 0xAA, \"header\");\n")
            sb.WriteString("    checkEq(buf[1], 0x02, \"version\");\n")
            sb.WriteString("    checkEq(buf[4], 0x02, \"magic_color\");\n")
        }
        fmt.Fprintf(&sb, "    const d = new %s.%s();\n", nsPrefix, sc.StructName)
        fmt.Fprintf(&sb, "    const _n = %s.%s.decode(d, buf);\n", nsPrefix, sc.StructName)
        if sc.IsDynamic {
            sb.WriteString("    check(_n > 0, \"decode > 0\");\n")
        } else {
            fmt.Fprintf(&sb, "    check(_n === %s.%s.size(), \"decode size\");\n", nsPrefix, sc.StructName)
        }
        for _, af := range c.resolveAssert() {
            sb.WriteString(emitJS_assertField("d", af, "    ", nsPrefix))
        }
        for _, e := range c.Errors {
            fmt.Fprintf(&sb, "    // decode-error: %s\n", e.Name)
            sb.WriteString("    {\n")
            sb.WriteString("        const bad = Array.from(buf);\n")
            for _, p := range e.Patches {
                fmt.Fprintf(&sb, "        bad[%d] = 0x%02X;\n", p.Offset, p.Value)
            }
            fmt.Fprintf(&sb, "        const err = new %s.%s();\n", nsPrefix, sc.StructName)
            fmt.Fprintf(&sb, "        check(%s.%s.decode(err, bad) === %d, \"%s\");\n",
                nsPrefix, sc.StructName, e.ExpectedRet, e.Name)
            sb.WriteString("    }\n")
        }
        sb.WriteString("}\n")
    }

    if len(sc.DecodeSizeChecks) > 0 {
        sb.WriteString(emitJS_decodeSize(sc, nsPrefix))
    }
    return sb.String()
}

func jsNS(sc Scenario) string {
    if sc.Package == "bitwid" {
        return "bw"
    }
    return "pkg"
}

func emitJS_setField(target string, fv FieldVal, indent, ns string) string {
    return emitJS_setNamed(target, fv.Name, fv.V, indent, ns)
}

func emitJS_setNamed(target, name string, v Val, indent, ns string) string {
    prop := camelCase(name)
    expr := emitJS_valueExpr(v, indent, ns, target+"_"+name)
    if expr.body != "" {
        return expr.body + fmt.Sprintf("%s%s.%s = %s;\n", indent, target, prop, expr.expr)
    }
    return fmt.Sprintf("%s%s.%s = %s;\n", indent, target, prop, expr.expr)
}

// jsValExpr is a (body, expr) pair where `body` contains preparatory
// statements (e.g. struct array element construction) and `expr` is the
// final expression to use as a value.
type jsValExpr struct {
    body string
    expr string
}

func emitJS_valueExpr(v Val, indent, ns, hint string) jsValExpr {
    switch v.Kind {
    case VKBool:
        if v.U != 0 {
            return jsValExpr{expr: "true"}
        }
        return jsValExpr{expr: "false"}
    case VKU8, VKU16, VKU32:
        return jsValExpr{expr: fmt.Sprintf("0x%X", v.U)}
    case VKI8, VKI16, VKI32:
        return jsValExpr{expr: fmt.Sprintf("%d", v.I)}
    case VKU64:
        return jsValExpr{expr: fmt.Sprintf("0x%Xn", v.U)}
    case VKI64:
        if v.I < 0 {
            return jsValExpr{expr: fmt.Sprintf("BigInt(\"%d\")", v.I)}
        }
        return jsValExpr{expr: fmt.Sprintf("0x%Xn", uint64(v.I))}
    case VKF32:
        return jsValExpr{expr: fmt.Sprintf("f32FromBits(0x%08X)", uint32(v.U))}
    case VKF64:
        return jsValExpr{expr: fmt.Sprintf("f64FromBits(0x%016Xn)", v.U)}
    case VKEnum:
        return jsValExpr{expr: fmt.Sprintf("%s.%s.%s", ns, v.EnumType, v.EnumName)}
    case VKString:
        return jsValExpr{expr: jsStringLit(v.Str)}
    case VKBytes:
        if len(v.Bytes) == 0 {
            return jsValExpr{expr: "[]"}
        }
        return jsValExpr{expr: fmt.Sprintf("[%s]", jsByteList(v.Bytes))}
    case VKStruct:
        var sb strings.Builder
        tmp := jsTempName(hint)
        fmt.Fprintf(&sb, "%sconst %s = new %s.%s();\n", indent, tmp, ns, v.Struct.Type)
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitJS_setNamed(tmp, f.Name, f.V, indent, ns))
        }
        return jsValExpr{body: sb.String(), expr: tmp}
    case VKArray:
        var sb strings.Builder
        var items []string
        for i, item := range v.Array.Items {
            sub := emitJS_valueExpr(item, indent, ns, fmt.Sprintf("%s_%d", hint, i))
            sb.WriteString(sub.body)
            items = append(items, sub.expr)
        }
        return jsValExpr{body: sb.String(), expr: "[" + strings.Join(items, ", ") + "]"}
    }
    return jsValExpr{}
}

func emitJS_assertField(target string, af AssertField, indent, ns string) string {
    return emitJS_assertNamed(target, af.Name, af.V, af.Tol, indent, ns, af.Name)
}

func emitJS_assertNamed(target, name string, v Val, tol float64, indent, ns, label string) string {
    prop := camelCase(name)
    accessor := fmt.Sprintf("%s.%s", target, prop)
    return emitJS_assertExpr(accessor, v, tol, indent, ns, label)
}

func emitJS_assertExpr(accessor string, v Val, tol float64, indent, ns, label string) string {
    switch v.Kind {
    case VKBool:
        return fmt.Sprintf("%scheckEq(%s, %t, \"%s\");\n", indent, accessor, v.U != 0, label)
    case VKU8, VKU16:
        return fmt.Sprintf("%scheckEq(%s, 0x%X, \"%s\");\n", indent, accessor, v.U, label)
    case VKU32:
        // u32 round-trip can come back signed via int32 view in JS — coerce.
        return fmt.Sprintf("%scheckEq(%s >>> 0, 0x%X, \"%s\");\n", indent, accessor, uint32(v.U), label)
    case VKI8, VKI16, VKI32:
        return fmt.Sprintf("%scheckEq(%s, %d, \"%s\");\n", indent, accessor, v.I, label)
    case VKU64:
        return fmt.Sprintf("%scheckBig(%s, 0x%Xn, \"%s\");\n", indent, accessor, v.U, label)
    case VKI64:
        if v.I < 0 {
            return fmt.Sprintf("%scheckBig(%s, BigInt(\"%d\"), \"%s\");\n", indent, accessor, v.I, label)
        }
        return fmt.Sprintf("%scheckBig(%s, 0x%Xn, \"%s\");\n", indent, accessor, uint64(v.I), label)
    case VKF32:
        if tol > 0 {
            return fmt.Sprintf("%scheckNear(%s, f32FromBits(0x%08X), %g, \"%s\");\n",
                indent, accessor, uint32(v.U), tol, label)
        }
        return fmt.Sprintf("%scheckEq(f32ToBits(%s) >>> 0, 0x%08X, \"%s bits\");\n",
            indent, accessor, uint32(v.U), label)
    case VKF64:
        if tol > 0 {
            return fmt.Sprintf("%scheckNear(%s, f64FromBits(0x%016Xn), %g, \"%s\");\n",
                indent, accessor, v.U, tol, label)
        }
        return fmt.Sprintf("%scheckBig(f64ToBits(%s), 0x%016Xn, \"%s bits\");\n",
            indent, accessor, v.U, label)
    case VKEnum:
        // Bubbler JS targets emit enum values as their string name.
        return fmt.Sprintf("%scheckEq(%s, \"%s\", \"%s\");\n", indent, accessor, v.EnumName, label)
    case VKString:
        return fmt.Sprintf("%scheckEq(%s, %s, \"%s\");\n", indent, accessor, jsStringLit(v.Str), label)
    case VKBytes:
        if len(v.Bytes) == 0 {
            return fmt.Sprintf("%scheck(%s.length === 0, \"%s empty\");\n", indent, accessor, label)
        }
        var sb strings.Builder
        fmt.Fprintf(&sb, "%scheck(%s.length === %d, \"%s length\");\n",
            indent, accessor, len(v.Bytes), label)
        for i, b := range v.Bytes {
            fmt.Fprintf(&sb, "%scheckEq(%s[%d], 0x%02X, \"%s[%d]\");\n",
                indent, accessor, i, b, label, i)
        }
        return sb.String()
    case VKStruct:
        var sb strings.Builder
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitJS_assertExpr(accessor+"."+camelCase(f.Name), f.V, tol, indent, ns,
                fmt.Sprintf("%s.%s", label, f.Name)))
        }
        return sb.String()
    case VKArray:
        var sb strings.Builder
        for i, it := range v.Array.Items {
            sb.WriteString(emitJS_assertExpr(fmt.Sprintf("%s[%d]", accessor, i), it, tol, indent, ns,
                fmt.Sprintf("%s[%d]", label, i)))
        }
        return sb.String()
    }
    return ""
}

func emitJS_decodeSize(sc Scenario, ns string) string {
    var sb strings.Builder
    sb.WriteString("// --- decode_size boundary checks ---\n")
    sb.WriteString("{\n")

    var needSource bool
    var srcCase string
    for _, ds := range sc.DecodeSizeChecks {
        if ds.SourceCase != "" {
            needSource = true
            srcCase = ds.SourceCase
        }
    }
    if needSource {
        var c Case
        for _, cc := range sc.Cases {
            if cc.Name == srcCase {
                c = cc
                break
            }
        }
        fmt.Fprintf(&sb, "    const _src = new %s.%s();\n", ns, sc.StructName)
        for _, fv := range c.Setup {
            sb.WriteString(emitJS_setNamed("_src", fv.Name, fv.V, "    ", ns))
        }
        fmt.Fprintf(&sb, "    const _full = %s.%s.encode(_src);\n", ns, sc.StructName)
    }

    for _, ds := range sc.DecodeSizeChecks {
        fmt.Fprintf(&sb, "    // %s\n", ds.Name)
        if ds.SourceCase != "" {
            if ds.Truncate == 0 {
                sb.WriteString("    checkEq(decodeSizeDynamic(_full, 0), _full.length, \"complete\");\n")
            } else {
                fmt.Fprintf(&sb, "    checkEq(decodeSizeDynamic(Array.from(_full).slice(0, _full.length - %d), 0), -_full.length, \"truncate %d\");\n",
                    ds.Truncate, ds.Truncate)
            }
        } else {
            fmt.Fprintf(&sb, "    checkEq(decodeSizeDynamic([%s], 0), %d, \"%s\");\n",
                jsByteList(ds.Bytes), ds.Expected, ds.Name)
        }
    }
    sb.WriteString("}\n")
    return sb.String()
}

func emitJS_getterSetter(sc Scenario) string {
    var sb strings.Builder
    fmt.Fprintf(&sb, "// %s — %s\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, "g_current = \"%s\";\n", sc.StructName)
    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "// case: %s\n", c.Name)
        sb.WriteString("{\n")
        fmt.Fprintf(&sb, "    const s = new pkg.%s();\n", sc.StructName)
        for _, ap := range c.Accessors {
            fmt.Fprintf(&sb, "    s.%s = f64FromBits(0x%016Xn);\n", camelCase(ap.SetterName), ap.SetArg.U)
        }
        roundTrip := false
        for _, ap := range c.Accessors {
            if !ap.NoRoundTrip {
                roundTrip = true
                break
            }
        }
        if roundTrip {
            fmt.Fprintf(&sb, "    const buf = pkg.%s.encode(s);\n", sc.StructName)
            fmt.Fprintf(&sb, "    const d = new pkg.%s();\n", sc.StructName)
            fmt.Fprintf(&sb, "    check(pkg.%s.decode(d, buf) === pkg.%s.size(), \"decode size\");\n",
                sc.StructName, sc.StructName)
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "    checkNear(d.%s, f64FromBits(0x%016Xn), %g, \"%s\");\n",
                    camelCase(ap.GetterName), ap.Expected.U, tol, ap.GetterName)
            }
        } else {
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "    checkNear(s.%s, f64FromBits(0x%016Xn), %g, \"%s\");\n",
                    camelCase(ap.GetterName), ap.Expected.U, tol, ap.GetterName)
            }
        }
        sb.WriteString("}\n")
    }
    return sb.String()
}

// ──────────────────────────────────────────────────────────────────────────
// Value formatting
// ──────────────────────────────────────────────────────────────────────────

func jsStringLit(s string) string {
    var sb strings.Builder
    sb.WriteByte('"')
    for _, r := range s {
        switch r {
        case '\\':
            sb.WriteString("\\\\")
        case '"':
            sb.WriteString("\\\"")
        case '\n':
            sb.WriteString("\\n")
        case '\r':
            sb.WriteString("\\r")
        case '\t':
            sb.WriteString("\\t")
        default:
            if r < 0x20 {
                fmt.Fprintf(&sb, "\\u%04x", r)
            } else if r > 0xFFFF {
                fmt.Fprintf(&sb, "\\u{%x}", r)
            } else {
                sb.WriteRune(r)
            }
        }
    }
    sb.WriteByte('"')
    return sb.String()
}

func jsByteList(b []byte) string {
    parts := make([]string, len(b))
    for i, v := range b {
        parts[i] = fmt.Sprintf("0x%02X", v)
    }
    return strings.Join(parts, ", ")
}

func jsTempName(s string) string {
    var sb strings.Builder
    sb.WriteByte('_')
    for _, r := range s {
        if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
            sb.WriteRune(r)
        } else {
            sb.WriteByte('_')
        }
    }
    return sb.String()
}
