package main

import (
    "fmt"
    "strings"
)

// EmitJava produces e2e/tests/java/Main.java from the spec.
func EmitJava(spec *Spec) string {
    var sb strings.Builder

    sb.WriteString(`/*
 * Bubbler E2E Test - Java target
 *
 * GENERATED by e2e/spec; DO NOT EDIT BY HAND.
 * Source of truth: e2e/spec/scenarios.go
 *
 * Compile (from this directory, after code-gen step):
 *   javac -encoding UTF-8 -d out gen/com/example/testpkg/*.java gen/com/example/bitwid/*.java
 *   javac -encoding UTF-8 -cp out -d out Main.java
 *   java -cp out Main
 */
import com.example.testpkg.*;
import com.example.bitwid.*;

public class Main {
    private static int pass = 0;
    private static int fail = 0;
    private static String current = "";

    static void check(boolean cond, String msg) {
        if (cond) { pass++; }
        else { System.err.println("  FAIL [" + current + "] " + msg); fail++; }
    }
    static void checkEq(long a, long b, String msg) {
        check(a == b, msg + " (got " + a + ", want " + b + ")");
    }
    static void checkNear(double a, double b, double eps, String msg) {
        check(Math.abs(a - b) < eps, msg + " (got " + a + ", want ~" + b + ")");
    }

`)

    for _, sc := range spec.Scenarios {
        sb.WriteString(emitJava_scenario(sc))
        sb.WriteString("\n")
    }

    sb.WriteString("    public static void main(String[] args) {\n")
    sb.WriteString("        System.out.println(\"=== Bubbler E2E Test - Java ===\\n\");\n")
    for _, sc := range spec.Scenarios {
        fmt.Fprintf(&sb, "        test_%s();\n", scLowerName(sc))
    }
    sb.WriteString("        System.out.printf(\"%n=== Results: %d passed, %d failed ===%n\", pass, fail);\n")
    sb.WriteString("        System.exit(fail > 0 ? 1 : 0);\n")
    sb.WriteString("    }\n")
    sb.WriteString("}\n")
    return sb.String()
}

func emitJava_scenario(sc Scenario) string {
    if sc.StructName == "GetterSetter" {
        return emitJava_getterSetter(sc)
    }
    var sb strings.Builder
    fmt.Fprintf(&sb, "    /* %s — %s */\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, "    static void test_%s() {\n", scLowerName(sc))
    fmt.Fprintf(&sb, "        current = \"%s\";\n", sc.StructName)

    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "        /* case: %s */\n", c.Name)
        sb.WriteString("        {\n")
        fmt.Fprintf(&sb, "            %s s = new %s();\n", sc.StructName, sc.StructName)
        for _, fv := range c.Setup {
            sb.WriteString(emitJava_setField("s", fv, "            "))
        }
        sb.WriteString("            byte[] buf = s.encode();\n")
        if !sc.IsDynamic {
            fmt.Fprintf(&sb, "            check(buf.length == %s.size(), \"encode length\");\n", sc.StructName)
        }
        if sc.StructName == "BigEndianFields" {
            sb.WriteString("            checkEq(Byte.toUnsignedInt(buf[0]), 0xBE, \"buf[0]=0xBE\");\n")
            sb.WriteString("            checkEq(Byte.toUnsignedInt(buf[1]), 0x12, \"buf[1]=0x12\");\n")
            sb.WriteString("            checkEq(Byte.toUnsignedInt(buf[2]), 0x34, \"buf[2]=0x34\");\n")
        }
        if sc.StructName == "ConstantFields" {
            sb.WriteString("            checkEq(Byte.toUnsignedInt(buf[0]), 0xAA, \"header\");\n")
            sb.WriteString("            checkEq(Byte.toUnsignedInt(buf[1]), 0x02, \"version\");\n")
            sb.WriteString("            checkEq(Byte.toUnsignedInt(buf[4]), 0x02, \"magic_color\");\n")
        }
        fmt.Fprintf(&sb, "            %s d = new %s();\n", sc.StructName, sc.StructName)
        if sc.IsDynamic {
            sb.WriteString("            int _n = d.decode(buf);\n")
            sb.WriteString("            check(_n > 0, \"decode > 0\");\n")
        } else {
            fmt.Fprintf(&sb, "            check(d.decode(buf) == %s.size(), \"decode size\");\n", sc.StructName)
        }
        for _, af := range c.resolveAssert() {
            sb.WriteString(emitJava_assertField("d", af, "            "))
        }
        for _, e := range c.Errors {
            fmt.Fprintf(&sb, "            /* decode-error: %s */\n", e.Name)
            sb.WriteString("            {\n")
            sb.WriteString("                byte[] bad = buf.clone();\n")
            for _, p := range e.Patches {
                fmt.Fprintf(&sb, "                bad[%d] = (byte) 0x%02X;\n", p.Offset, p.Value)
            }
            fmt.Fprintf(&sb, "                %s err = new %s();\n", sc.StructName, sc.StructName)
            fmt.Fprintf(&sb, "                checkEq(err.decode(bad), %d, \"%s\");\n", e.ExpectedRet, e.Name)
            sb.WriteString("            }\n")
        }
        sb.WriteString("        }\n")
    }

    if len(sc.DecodeSizeChecks) > 0 {
        sb.WriteString(emitJava_decodeSize(sc))
    }
    sb.WriteString("    }\n")
    return sb.String()
}

// emitJava_setField sets fv on the variable named target (e.g. "s") via the
// generated setter API. Handles all kinds including arrays of struct/enum.
func emitJava_setField(target string, fv FieldVal, indent string) string {
    return emitJava_setNamed(target, fv.Name, fv.V, indent)
}

func emitJava_setNamed(target, name string, v Val, indent string) string {
    setter := "set" + pascalCase(name)
    setterAt := "set" + pascalCase(name) + "At"

    switch v.Kind {
    case VKBool:
        return fmt.Sprintf("%s%s.%s(%s);\n", indent, target, setter, javaBool(v))
    case VKU8:
        return fmt.Sprintf("%s%s.%s((byte) %d);\n", indent, target, setter, uint8(v.U))
    case VKU16:
        return fmt.Sprintf("%s%s.%s((short) %d);\n", indent, target, setter, uint16(v.U))
    case VKU32:
        return fmt.Sprintf("%s%s.%s(%s);\n", indent, target, setter, javaIntLit(v))
    case VKU64:
        return fmt.Sprintf("%s%s.%s(%sL);\n", indent, target, setter, javaUInt64Literal(v.U))
    case VKI8:
        return fmt.Sprintf("%s%s.%s((byte) %d);\n", indent, target, setter, int8(v.I))
    case VKI16:
        return fmt.Sprintf("%s%s.%s((short) %d);\n", indent, target, setter, int16(v.I))
    case VKI32:
        return fmt.Sprintf("%s%s.%s(%d);\n", indent, target, setter, int32(v.I))
    case VKI64:
        return fmt.Sprintf("%s%s.%s(%dL);\n", indent, target, setter, v.I)
    case VKF32:
        return fmt.Sprintf("%s%s.%s(Float.intBitsToFloat(0x%08X));\n",
            indent, target, setter, uint32(v.U))
    case VKF64:
        return fmt.Sprintf("%s%s.%s(Double.longBitsToDouble(0x%016XL));\n",
            indent, target, setter, v.U)
    case VKEnum:
        return fmt.Sprintf("%s%s.%s(%s.%s);\n",
            indent, target, setter, v.EnumType, v.EnumName)
    case VKString:
        return fmt.Sprintf("%s%s.%s(%s);\n", indent, target, setter, javaStringLit(v.Str))
    case VKBytes:
        if len(v.Bytes) == 0 {
            return fmt.Sprintf("%s%s.%s(new byte[0]);\n", indent, target, setter)
        }
        return fmt.Sprintf("%s%s.%s(new byte[]{%s});\n", indent, target, setter, javaByteList(v.Bytes))
    case VKStruct:
        var sb strings.Builder
        tmp := javaTempName(target + "_" + name)
        fmt.Fprintf(&sb, "%s%s %s = new %s();\n", indent, v.Struct.Type, tmp, v.Struct.Type)
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitJava_setNamed(tmp, f.Name, f.V, indent))
        }
        fmt.Fprintf(&sb, "%s%s.%s(%s);\n", indent, target, setter, tmp)
        return sb.String()
    case VKArray:
        var sb strings.Builder
        for i, item := range v.Array.Items {
            sb.WriteString(emitJava_setAt(target, setterAt, i, item, indent))
        }
        return sb.String()
    }
    return ""
}

func emitJava_setAt(target, setterAt string, i int, v Val, indent string) string {
    switch v.Kind {
    case VKU8, VKI8:
        var n int64
        if v.Kind == VKU8 {
            n = int64(int8(uint8(v.U)))
        } else {
            n = int64(int8(v.I))
        }
        return fmt.Sprintf("%s%s.%s(%d, (byte) %d);\n", indent, target, setterAt, i, n)
    case VKU16, VKI16:
        var n int64
        if v.Kind == VKU16 {
            n = int64(int16(uint16(v.U)))
        } else {
            n = int64(int16(v.I))
        }
        return fmt.Sprintf("%s%s.%s(%d, (short) %d);\n", indent, target, setterAt, i, n)
    case VKU32:
        return fmt.Sprintf("%s%s.%s(%d, %s);\n", indent, target, setterAt, i, javaIntLit(v))
    case VKU64:
        return fmt.Sprintf("%s%s.%s(%d, %sL);\n", indent, target, setterAt, i, javaUInt64Literal(v.U))
    case VKI32:
        return fmt.Sprintf("%s%s.%s(%d, %d);\n", indent, target, setterAt, i, int32(v.I))
    case VKI64:
        return fmt.Sprintf("%s%s.%s(%d, %dL);\n", indent, target, setterAt, i, v.I)
    case VKF32:
        return fmt.Sprintf("%s%s.%s(%d, Float.intBitsToFloat(0x%08X));\n",
            indent, target, setterAt, i, uint32(v.U))
    case VKF64:
        return fmt.Sprintf("%s%s.%s(%d, Double.longBitsToDouble(0x%016XL));\n",
            indent, target, setterAt, i, v.U)
    case VKEnum:
        return fmt.Sprintf("%s%s.%s(%d, %s.%s);\n", indent, target, setterAt, i,
            v.EnumType, v.EnumName)
    case VKStruct:
        var sb strings.Builder
        tmp := javaTempName(fmt.Sprintf("%s_%s_%d", target, setterAt, i))
        fmt.Fprintf(&sb, "%s%s %s = new %s();\n", indent, v.Struct.Type, tmp, v.Struct.Type)
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitJava_setNamed(tmp, f.Name, f.V, indent))
        }
        fmt.Fprintf(&sb, "%s%s.%s(%d, %s);\n", indent, target, setterAt, i, tmp)
        return sb.String()
    }
    return ""
}

func emitJava_assertField(target string, af AssertField, indent string) string {
    return emitJava_assertNamed(target, af.Name, af.V, af.Tol, indent)
}

func emitJava_assertNamed(target, name string, v Val, tol float64, indent string) string {
    getter := "get" + pascalCase(name)
    getterAt := "get" + pascalCase(name) + "At"
    msg := name

    switch v.Kind {
    case VKBool:
        if v.U != 0 {
            return fmt.Sprintf("%scheck(%s.%s() == true, \"%s\");\n", indent, target, getter, msg)
        }
        return fmt.Sprintf("%scheck(%s.%s() == false, \"%s\");\n", indent, target, getter, msg)
    case VKU8:
        return fmt.Sprintf("%scheckEq(Byte.toUnsignedInt(%s.%s()), %d, \"%s\");\n",
            indent, target, getter, uint8(v.U), msg)
    case VKU16:
        return fmt.Sprintf("%scheckEq(Short.toUnsignedInt(%s.%s()), %d, \"%s\");\n",
            indent, target, getter, uint16(v.U), msg)
    case VKU32:
        return fmt.Sprintf("%scheckEq(Integer.toUnsignedLong(%s.%s()), %sL, \"%s\");\n",
            indent, target, getter, javaUInt32Literal(uint32(v.U)), msg)
    case VKU64:
        return fmt.Sprintf("%scheck(Long.compareUnsigned(%s.%s(), %sL) == 0, \"%s\");\n",
            indent, target, getter, javaUInt64Literal(v.U), msg)
    case VKI8, VKI16, VKI32:
        return fmt.Sprintf("%scheckEq(%s.%s(), %dL, \"%s\");\n",
            indent, target, getter, v.I, msg)
    case VKI64:
        return fmt.Sprintf("%scheckEq(%s.%s(), %dL, \"%s\");\n",
            indent, target, getter, v.I, msg)
    case VKF32:
        if tol > 0 {
            return fmt.Sprintf("%scheckNear(%s.%s(), Float.intBitsToFloat(0x%08X), %g, \"%s\");\n",
                indent, target, getter, uint32(v.U), tol, msg)
        }
        return fmt.Sprintf("%scheckEq(Integer.toUnsignedLong(Float.floatToRawIntBits(%s.%s())), Integer.toUnsignedLong(0x%08X), \"%s bits\");\n",
            indent, target, getter, uint32(v.U), msg)
    case VKF64:
        if tol > 0 {
            return fmt.Sprintf("%scheckNear(%s.%s(), Double.longBitsToDouble(0x%016XL), %g, \"%s\");\n",
                indent, target, getter, v.U, tol, msg)
        }
        return fmt.Sprintf("%scheck(Double.doubleToRawLongBits(%s.%s()) == 0x%016XL, \"%s bits\");\n",
            indent, target, getter, v.U, msg)
    case VKEnum:
        return fmt.Sprintf("%scheck(%s.%s() == %s.%s, \"%s\");\n",
            indent, target, getter, v.EnumType, v.EnumName, msg)
    case VKString:
        return fmt.Sprintf("%scheck(%s.equals(%s.%s()), \"%s\");\n",
            indent, javaStringLit(v.Str), target, getter, msg)
    case VKBytes:
        if len(v.Bytes) == 0 {
            return fmt.Sprintf("%scheck(%s.%s().length == 0, \"%s empty\");\n",
                indent, target, getter, msg)
        }
        return fmt.Sprintf("%scheck(java.util.Arrays.equals(%s.%s(), new byte[]{%s}), \"%s\");\n",
            indent, target, getter, javaByteList(v.Bytes), msg)
    case VKStruct:
        var sb strings.Builder
        tmp := javaTempName(target + "_g_" + name)
        fmt.Fprintf(&sb, "%s%s %s = %s.%s();\n", indent, v.Struct.Type, tmp, target, getter)
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitJava_assertNamed(tmp, f.Name, f.V, tol, indent))
        }
        return sb.String()
    case VKArray:
        var sb strings.Builder
        for i, it := range v.Array.Items {
            sb.WriteString(emitJava_assertAt(target, getterAt, i, it, tol, indent, msg))
        }
        return sb.String()
    }
    return ""
}

func emitJava_assertAt(target, getterAt string, i int, v Val, tol float64, indent, msg string) string {
    label := fmt.Sprintf("%s[%d]", msg, i)
    switch v.Kind {
    case VKU8:
        return fmt.Sprintf("%scheckEq(Byte.toUnsignedInt(%s.%s(%d)), %d, \"%s\");\n",
            indent, target, getterAt, i, uint8(v.U), label)
    case VKU16:
        return fmt.Sprintf("%scheckEq(Short.toUnsignedInt(%s.%s(%d)), %d, \"%s\");\n",
            indent, target, getterAt, i, uint16(v.U), label)
    case VKU32:
        return fmt.Sprintf("%scheckEq(Integer.toUnsignedLong(%s.%s(%d)), %sL, \"%s\");\n",
            indent, target, getterAt, i, javaUInt32Literal(uint32(v.U)), label)
    case VKU64:
        return fmt.Sprintf("%scheck(Long.compareUnsigned(%s.%s(%d), %sL) == 0, \"%s\");\n",
            indent, target, getterAt, i, javaUInt64Literal(v.U), label)
    case VKI8, VKI16, VKI32:
        return fmt.Sprintf("%scheckEq(%s.%s(%d), %dL, \"%s\");\n",
            indent, target, getterAt, i, v.I, label)
    case VKI64:
        return fmt.Sprintf("%scheckEq(%s.%s(%d), %dL, \"%s\");\n",
            indent, target, getterAt, i, v.I, label)
    case VKF32:
        if tol > 0 {
            return fmt.Sprintf("%scheckNear(%s.%s(%d), Float.intBitsToFloat(0x%08X), %g, \"%s\");\n",
                indent, target, getterAt, i, uint32(v.U), tol, label)
        }
        return fmt.Sprintf("%scheckEq(Integer.toUnsignedLong(Float.floatToRawIntBits(%s.%s(%d))), Integer.toUnsignedLong(0x%08X), \"%s bits\");\n",
            indent, target, getterAt, i, uint32(v.U), label)
    case VKF64:
        if tol > 0 {
            return fmt.Sprintf("%scheckNear(%s.%s(%d), Double.longBitsToDouble(0x%016XL), %g, \"%s\");\n",
                indent, target, getterAt, i, v.U, tol, label)
        }
        return fmt.Sprintf("%scheck(Double.doubleToRawLongBits(%s.%s(%d)) == 0x%016XL, \"%s bits\");\n",
            indent, target, getterAt, i, v.U, label)
    case VKEnum:
        return fmt.Sprintf("%scheck(%s.%s(%d) == %s.%s, \"%s\");\n",
            indent, target, getterAt, i, v.EnumType, v.EnumName, label)
    case VKStruct:
        var sb strings.Builder
        tmp := javaTempName(fmt.Sprintf("%s_g_%s_%d", target, getterAt, i))
        fmt.Fprintf(&sb, "%s%s %s = %s.%s(%d);\n", indent, v.Struct.Type, tmp, target, getterAt, i)
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitJava_assertNamed(tmp, f.Name, f.V, tol, indent))
        }
        return sb.String()
    }
    return ""
}

func emitJava_decodeSize(sc Scenario) string {
    var sb strings.Builder
    sb.WriteString("        /* --- decode_size boundary checks --- */\n")
    sb.WriteString("        {\n")

    var needSource bool
    var srcCase string
    for _, ds := range sc.DecodeSizeChecks {
        if ds.SourceCase != "" {
            needSource = true
            srcCase = ds.SourceCase
        }
    }
    if needSource {
        var c Case
        for _, cc := range sc.Cases {
            if cc.Name == srcCase {
                c = cc
                break
            }
        }
        fmt.Fprintf(&sb, "            %s src = new %s();\n", sc.StructName, sc.StructName)
        for _, fv := range c.Setup {
            sb.WriteString(emitJava_setNamed("src", fv.Name, fv.V, "            "))
        }
        sb.WriteString("            byte[] full = src.encode();\n")
    }
    fmt.Fprintf(&sb, "            %s probe = new %s();\n", sc.StructName, sc.StructName)
    for _, ds := range sc.DecodeSizeChecks {
        fmt.Fprintf(&sb, "            /* %s */\n", ds.Name)
        if ds.SourceCase != "" {
            if ds.Truncate == 0 {
                sb.WriteString("            checkEq(probe.decodeSize(full), full.length, \"complete\");\n")
            } else {
                fmt.Fprintf(&sb, "            checkEq(probe.decodeSize(java.util.Arrays.copyOf(full, full.length - %d)), -full.length, \"truncate %d\");\n",
                    ds.Truncate, ds.Truncate)
            }
        } else {
            fmt.Fprintf(&sb, "            checkEq(probe.decodeSize(new byte[]{%s}), %d, \"%s\");\n",
                javaByteList(ds.Bytes), ds.Expected, ds.Name)
        }
    }
    sb.WriteString("        }\n")
    return sb.String()
}

func emitJava_getterSetter(sc Scenario) string {
    var sb strings.Builder
    fmt.Fprintf(&sb, "    /* %s — %s */\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, "    static void test_%s() {\n", scLowerName(sc))
    fmt.Fprintf(&sb, "        current = \"%s\";\n", sc.StructName)
    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "        /* case: %s */\n", c.Name)
        sb.WriteString("        {\n")
        fmt.Fprintf(&sb, "            %s s = new %s();\n", sc.StructName, sc.StructName)
        for _, ap := range c.Accessors {
            fmt.Fprintf(&sb, "            s.set%s(Double.longBitsToDouble(0x%016XL));\n",
                pascalCase(ap.SetterName), ap.SetArg.U)
        }
        roundTrip := false
        for _, ap := range c.Accessors {
            if !ap.NoRoundTrip {
                roundTrip = true
                break
            }
        }
        if roundTrip {
            sb.WriteString("            byte[] buf = s.encode();\n")
            fmt.Fprintf(&sb, "            %s d = new %s();\n", sc.StructName, sc.StructName)
            fmt.Fprintf(&sb, "            check(d.decode(buf) == %s.size(), \"decode size\");\n", sc.StructName)
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "            checkNear(d.get%s(), Double.longBitsToDouble(0x%016XL), %g, \"%s\");\n",
                    pascalCase(ap.GetterName), ap.Expected.U, tol, ap.GetterName)
            }
        } else {
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "            checkNear(s.get%s(), Double.longBitsToDouble(0x%016XL), %g, \"%s\");\n",
                    pascalCase(ap.GetterName), ap.Expected.U, tol, ap.GetterName)
            }
        }
        sb.WriteString("        }\n")
    }
    sb.WriteString("    }\n")
    return sb.String()
}

// ──────────────────────────────────────────────────────────────────────────
// Value formatting
// ──────────────────────────────────────────────────────────────────────────

func javaBool(v Val) string {
    if v.U != 0 {
        return "true"
    }
    return "false"
}

func javaIntLit(v Val) string {
    switch v.Kind {
    case VKU8:
        return fmt.Sprintf("%d", uint8(v.U))
    case VKU16:
        return fmt.Sprintf("%d", uint16(v.U))
    case VKU32:
        return javaUInt32Literal(uint32(v.U))
    case VKU64:
        return javaUInt64Literal(v.U)
    case VKI8:
        return fmt.Sprintf("%d", int8(v.I))
    case VKI16:
        return fmt.Sprintf("%d", int16(v.I))
    case VKI32:
        return fmt.Sprintf("%d", int32(v.I))
    case VKI64:
        return fmt.Sprintf("%dL", v.I)
    }
    return ""
}

// Java integer literals are 32-bit by default. 0xDEADBEEF must be expressed
// as a hex literal (sign-extends to int) — `(int)0xDEADBEEFL` works in
// expressions but causes `incompatible types` on direct assignment because
// the int literal would overflow.
//
// We sidestep by rendering as `0xXX...` and trusting Java's "any 32-bit hex
// literal is a valid int literal" rule.
func javaUInt32Literal(u uint32) string {
    return fmt.Sprintf("0x%08X", u)
}

func javaUInt64Literal(u uint64) string {
    return fmt.Sprintf("0x%016X", u)
}

func javaStringLit(s string) string {
    var sb strings.Builder
    sb.WriteByte('"')
    for _, r := range s {
        switch r {
        case '\\':
            sb.WriteString("\\\\")
        case '"':
            sb.WriteString("\\\"")
        case '\n':
            sb.WriteString("\\n")
        case '\r':
            sb.WriteString("\\r")
        case '\t':
            sb.WriteString("\\t")
        default:
            if r < 0x20 || r > 0x7E {
                if r > 0xFFFF {
                    fmt.Fprintf(&sb, "\\u%04X\\u%04X", 0xD800+((r-0x10000)>>10), 0xDC00+((r-0x10000)&0x3FF))
                } else {
                    fmt.Fprintf(&sb, "\\u%04X", r)
                }
            } else {
                sb.WriteRune(r)
            }
        }
    }
    sb.WriteByte('"')
    return sb.String()
}

func javaByteList(b []byte) string {
    parts := make([]string, len(b))
    for i, v := range b {
        if v >= 0x80 {
            parts[i] = fmt.Sprintf("(byte) 0x%02X", v)
        } else {
            parts[i] = fmt.Sprintf("0x%02X", v)
        }
    }
    return strings.Join(parts, ", ")
}

func javaTempName(s string) string {
    var sb strings.Builder
    sb.WriteByte('_')
    for _, r := range s {
        if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') {
            sb.WriteRune(r)
        } else {
            sb.WriteByte('_')
        }
    }
    return sb.String()
}
