package main

import (
    "fmt"
    "math"
    "strings"
)

// EmitC produces a complete e2e/tests/c/main.c source file from the spec.
func EmitC(spec *Spec) string {
    var sb strings.Builder

    sb.WriteString(`/*
 * Bubbler E2E Test - C target
 *
 * GENERATED by e2e/spec; DO NOT EDIT BY HAND.
 * Source of truth: e2e/spec/scenarios.go
 *
 * Build (from this directory, after code-gen step):
 *   gcc -std=c11 -Igen -o run_test main.c gen/testpkg.bb.c gen/bitwid.bb.c -lm
 */
#include "gen/testpkg.bb.h"
#include "gen/bitwid.bb.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

/* ------------------------------------------------------------------ */
/* Minimal test framework                                             */
/* ------------------------------------------------------------------ */
static int g_pass = 0;
static int g_fail = 0;
static const char *g_current = "";

static void _check(int cond, const char *expr, const char *file, int line) {
    if (cond) {
        g_pass++;
    } else {
        fprintf(stderr, "  FAIL [%s] %s:%d  %s\n", g_current, file, line, expr);
        g_fail++;
    }
}

#define CHECK(cond)         _check(!!(cond), #cond, __FILE__, __LINE__)
#define CHECK_EQ(a,b)       _check((a)==(b), #a " == " #b, __FILE__, __LINE__)
#define CHECK_NEAR(a,b,eps) _check(fabs((double)(a)-(double)(b))<(eps), \
                                #a " ~= " #b, __FILE__, __LINE__)

/* Bit-pattern helpers for IEEE-754 corner-case round-trips.            */
static float bb_f32_from_bits(uint32_t b) { float f; memcpy(&f, &b, 4); return f; }
static double bb_f64_from_bits(uint64_t b) { double f; memcpy(&f, &b, 8); return f; }
static uint32_t bb_f32_to_bits(float f) { uint32_t b; memcpy(&b, &f, 4); return b; }
static uint64_t bb_f64_to_bits(double f) { uint64_t b; memcpy(&b, &f, 8); return b; }

`)

    for _, sc := range spec.Scenarios {
        sb.WriteString(emitC_scenario(sc))
        sb.WriteString("\n")
    }

    // Entry point
    sb.WriteString("int main(void) {\n")
    sb.WriteString("    printf(\"=== Bubbler E2E Test - C ===\\n\\n\");\n")
    for _, sc := range spec.Scenarios {
        sb.WriteString(fmt.Sprintf("    test_%s();\n", scLowerName(sc)))
    }
    sb.WriteString("    printf(\"\\n=== Results: %d passed, %d failed ===\\n\", g_pass, g_fail);\n")
    sb.WriteString("    return g_fail > 0 ? 1 : 0;\n")
    sb.WriteString("}\n")
    return sb.String()
}

func scLowerName(sc Scenario) string {
    // SimpleScalars -> simple_scalars
    var sb strings.Builder
    for i, r := range sc.StructName {
        if i > 0 && r >= 'A' && r <= 'Z' {
            sb.WriteByte('_')
        }
        if r >= 'A' && r <= 'Z' {
            sb.WriteRune(r + 32)
        } else {
            sb.WriteRune(r)
        }
    }
    return sb.String()
}

func emitC_scenario(sc Scenario) string {
    // GetterSetter is special: it's all about accessor pairs, not field assignment.
    if sc.StructName == "GetterSetter" {
        return emitC_getterSetter(sc)
    }

    var sb strings.Builder
    fmt.Fprintf(&sb, "/* ============================================================\n")
    fmt.Fprintf(&sb, " * %s — %s\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, " * ============================================================ */\n")
    fmt.Fprintf(&sb, "static void test_%s(void) {\n", scLowerName(sc))
    fmt.Fprintf(&sb, "    g_current = \"%s\";\n", sc.StructName)

    for _, c := range sc.Cases {
        sb.WriteString(emitC_case(sc, c))
    }

    // DecodeSize checks for dynamic structs
    if len(sc.DecodeSizeChecks) > 0 {
        sb.WriteString(emitC_decodeSize(sc))
    }

    sb.WriteString("}\n")
    return sb.String()
}

func emitC_case(sc Scenario, c Case) string {
    var sb strings.Builder

    fmt.Fprintf(&sb, "    /* --- case: %s --- */\n", c.Name)
    fmt.Fprintf(&sb, "    {\n")

    // Build input struct via designated zero-init then per-field assignment.
    fmt.Fprintf(&sb, "        struct %s s = {0};\n", sc.StructName)
    for _, fv := range c.Setup {
        sb.WriteString(emitC_assign("s", fv))
    }

    // Encode buffer (fixed vs dynamic)
    if sc.IsDynamic {
        fmt.Fprintf(&sb, "        uint64_t _sz = %s_encode_size(&s);\n", sc.StructName)
        fmt.Fprintf(&sb, "        uint8_t *buf = (uint8_t *)malloc(_sz ? _sz : 1);\n")
        fmt.Fprintf(&sb, "        memset(buf, 0, _sz);\n")
        fmt.Fprintf(&sb, "        int64_t _enc = (int64_t)%s_encode(&s, buf);\n", sc.StructName)
        fmt.Fprintf(&sb, "        CHECK_EQ(_enc, (int64_t)_sz);\n")
    } else {
        fmt.Fprintf(&sb, "        uint8_t buf[%s_size];\n", sc.StructName)
        fmt.Fprintf(&sb, "        memset(buf, 0, sizeof(buf));\n")
        fmt.Fprintf(&sb, "        CHECK_EQ((int)%s_encode(&s, buf), (int)%s_size);\n",
            sc.StructName, sc.StructName)
    }

    // Special case: BigEndianFields case checks raw byte layout
    if sc.StructName == "BigEndianFields" {
        sb.WriteString("        CHECK_EQ(buf[0], 0xBE);\n")
        sb.WriteString("        CHECK_EQ(buf[1], 0x12);\n")
        sb.WriteString("        CHECK_EQ(buf[2], 0x34);\n")
        sb.WriteString("        CHECK_EQ(buf[3], 0xFF);\n")
        sb.WriteString("        CHECK_EQ(buf[6], 0xFF);\n")
    }
    if sc.StructName == "ConstantFields" {
        sb.WriteString("        CHECK_EQ(buf[0], 0xAA);\n")
        sb.WriteString("        CHECK_EQ(buf[1], 0x02);\n")
        sb.WriteString("        CHECK_EQ(buf[4], 0x02);\n")
    }

    // Decode and assert
    fmt.Fprintf(&sb, "        struct %s d = {0};\n", sc.StructName)
    if sc.IsDynamic {
        fmt.Fprintf(&sb, "        int64_t _dec = %s_decode(buf, &d);\n", sc.StructName)
        fmt.Fprintf(&sb, "        CHECK(_dec > 0);\n")
    } else {
        fmt.Fprintf(&sb, "        CHECK_EQ((int)%s_decode(buf, &d), (int)%s_size);\n",
            sc.StructName, sc.StructName)
    }
    for _, af := range c.resolveAssert() {
        sb.WriteString(emitC_assert("d", af))
    }

    // Decode-failure scenarios on a copy of buf
    for _, e := range c.Errors {
        fmt.Fprintf(&sb, "        /* decode-error: %s */\n", e.Name)
        fmt.Fprintf(&sb, "        {\n")
        fmt.Fprintf(&sb, "            uint8_t bad[%s_size]; memcpy(bad, buf, sizeof(bad));\n",
            sc.StructName)
        for _, p := range e.Patches {
            fmt.Fprintf(&sb, "            bad[%d] = 0x%02X;\n", p.Offset, p.Value)
        }
        fmt.Fprintf(&sb, "            struct %s err = {0};\n", sc.StructName)
        fmt.Fprintf(&sb, "            CHECK_EQ((long long)%s_decode(bad, &err), %dLL);\n",
            sc.StructName, e.ExpectedRet)
        fmt.Fprintf(&sb, "        }\n")
    }

    if sc.IsDynamic {
        fmt.Fprintf(&sb, "        free(buf);\n")
    }
    fmt.Fprintf(&sb, "    }\n")
    return sb.String()
}

func emitC_assign(target string, fv FieldVal) string {
    return emitC_assignVal(target+"."+fv.Name, fv.V, "        ")
}

// emitC_assignVal writes value v into the C lvalue `dst`. Indent is the
// leading whitespace per emitted line.
func emitC_assignVal(dst string, v Val, indent string) string {
    switch v.Kind {
    case VKBool:
        return fmt.Sprintf("%s%s = %s;\n", indent, dst, cBool(v))
    case VKU8, VKU16, VKU32, VKU64:
        return fmt.Sprintf("%s%s = %s;\n", indent, dst, cUInt(v))
    case VKI8, VKI16, VKI32, VKI64:
        return fmt.Sprintf("%s%s = %s;\n", indent, dst, cSInt(v))
    case VKF32:
        return fmt.Sprintf("%s%s = bb_f32_from_bits(0x%08XU);\n", indent, dst, uint32(v.U))
    case VKF64:
        return fmt.Sprintf("%s%s = bb_f64_from_bits(0x%016XULL);\n", indent, dst, v.U)
    case VKEnum:
        return fmt.Sprintf("%s%s = %s;\n", indent, dst, v.EnumName)
    case VKString:
        return fmt.Sprintf("%s%s = %s;\n", indent, dst, cStringLit(v.Str))
    case VKBytes:
        var sb strings.Builder
        if len(v.Bytes) == 0 {
            // Use NULL/0 length.
            fmt.Fprintf(&sb, "%s%s.data = NULL;\n", indent, dst)
            fmt.Fprintf(&sb, "%s%s.length = 0;\n", indent, dst)
            return sb.String()
        }
        // Emit a static buffer (each bytes assignment gets a unique block).
        fmt.Fprintf(&sb, "%s{\n", indent)
        fmt.Fprintf(&sb, "%s    static uint8_t _b[] = {%s};\n", indent, cByteList(v.Bytes))
        fmt.Fprintf(&sb, "%s    %s.data = _b;\n", indent, dst)
        fmt.Fprintf(&sb, "%s    %s.length = (uint64_t)sizeof(_b);\n", indent, dst)
        fmt.Fprintf(&sb, "%s}\n", indent)
        return sb.String()
    case VKStruct:
        var sb strings.Builder
        // Set each field in order.
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitC_assignVal(dst+"."+f.Name, f.V, indent))
        }
        return sb.String()
    case VKArray:
        var sb strings.Builder
        for i, item := range v.Array.Items {
            sb.WriteString(emitC_assignVal(fmt.Sprintf("%s[%d]", dst, i), item, indent))
        }
        return sb.String()
    }
    return fmt.Sprintf("%s/* unsupported kind for %s */\n", indent, dst)
}

func emitC_assert(target string, af AssertField) string {
    return emitC_assertVal(target+"."+af.Name, af.V, af.Tol, "        ")
}

func emitC_assertVal(dst string, v Val, tol float64, indent string) string {
    switch v.Kind {
    case VKBool:
        return fmt.Sprintf("%sCHECK_EQ((int)%s, %s);\n", indent, dst, cBool(v))
    case VKU8, VKU16:
        return fmt.Sprintf("%sCHECK_EQ((int)%s, %s);\n", indent, dst, cUInt(v))
    case VKU32:
        return fmt.Sprintf("%sCHECK_EQ(%s, %sU);\n", indent, dst, cUIntRaw(v))
    case VKU64:
        return fmt.Sprintf("%sCHECK_EQ(%s, %sULL);\n", indent, dst, cUIntRaw(v))
    case VKI8, VKI16, VKI32:
        return fmt.Sprintf("%sCHECK_EQ((int64_t)%s, (int64_t)%s);\n", indent, dst, cSInt(v))
    case VKI64:
        return fmt.Sprintf("%sCHECK_EQ((long long)%s, (long long)%s);\n", indent, dst, cSInt(v))
    case VKF32:
        if tol > 0 {
            return fmt.Sprintf("%sCHECK_NEAR(%s, bb_f32_from_bits(0x%08XU), %g);\n",
                indent, dst, uint32(v.U), tol)
        }
        return fmt.Sprintf("%sCHECK_EQ((unsigned long)bb_f32_to_bits(%s), 0x%08XUL);\n",
            indent, dst, uint32(v.U))
    case VKF64:
        if tol > 0 {
            return fmt.Sprintf("%sCHECK_NEAR(%s, bb_f64_from_bits(0x%016XULL), %g);\n",
                indent, dst, v.U, tol)
        }
        return fmt.Sprintf("%sCHECK_EQ((unsigned long long)bb_f64_to_bits(%s), 0x%016XULL);\n",
            indent, dst, v.U)
    case VKEnum:
        return fmt.Sprintf("%sCHECK_EQ((int)%s, (int)%s);\n", indent, dst, v.EnumName)
    case VKString:
        // d.label is char* in C; compare with strcmp.
        return fmt.Sprintf("%sCHECK(strcmp(%s, %s) == 0);\n", indent, dst, cStringLit(v.Str))
    case VKBytes:
        var sb strings.Builder
        fmt.Fprintf(&sb, "%sCHECK_EQ((int)%s.length, %d);\n", indent, dst, len(v.Bytes))
        if len(v.Bytes) > 0 {
            fmt.Fprintf(&sb, "%s{\n", indent)
            fmt.Fprintf(&sb, "%s    static const uint8_t _exp[] = {%s};\n", indent, cByteList(v.Bytes))
            fmt.Fprintf(&sb, "%s    CHECK(memcmp(%s.data, _exp, sizeof(_exp)) == 0);\n", indent, dst)
            fmt.Fprintf(&sb, "%s}\n", indent)
        }
        return sb.String()
    case VKStruct:
        var sb strings.Builder
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitC_assertVal(dst+"."+f.Name, f.V, tol, indent))
        }
        return sb.String()
    case VKArray:
        var sb strings.Builder
        for i, it := range v.Array.Items {
            sb.WriteString(emitC_assertVal(fmt.Sprintf("%s[%d]", dst, i), it, tol, indent))
        }
        return sb.String()
    }
    return fmt.Sprintf("%s/* unsupported assert */\n", indent)
}

func emitC_decodeSize(sc Scenario) string {
    var sb strings.Builder
    sb.WriteString("    /* --- decode_size boundary checks --- */\n")
    sb.WriteString("    {\n")

    // Generate any "complete_packet" / "truncate_one_byte" cases; they
    // need a freshly encoded source.
    var needSource bool
    var srcCase string
    for _, ds := range sc.DecodeSizeChecks {
        if ds.SourceCase != "" {
            needSource = true
            srcCase = ds.SourceCase
        }
    }
    if needSource {
        // Find the case named srcCase.
        var c Case
        for _, cc := range sc.Cases {
            if cc.Name == srcCase {
                c = cc
                break
            }
        }
        fmt.Fprintf(&sb, "        struct %s _src = {0};\n", sc.StructName)
        for _, fv := range c.Setup {
            sb.WriteString(emitC_assignVal("_src."+fv.Name, fv.V, "        "))
        }
        fmt.Fprintf(&sb, "        uint64_t _full_sz = %s_encode_size(&_src);\n", sc.StructName)
        fmt.Fprintf(&sb, "        uint8_t *_full = (uint8_t *)malloc(_full_sz ? _full_sz : 1);\n")
        fmt.Fprintf(&sb, "        %s_encode(&_src, _full);\n", sc.StructName)
    }

    for _, ds := range sc.DecodeSizeChecks {
        fmt.Fprintf(&sb, "        /* %s */\n", ds.Name)
        if ds.SourceCase != "" {
            if ds.Truncate == 0 {
                fmt.Fprintf(&sb, "        CHECK_EQ((long long)%s_decode_size(_full, _full_sz), (long long)_full_sz);\n",
                    sc.StructName)
            } else {
                fmt.Fprintf(&sb, "        CHECK_EQ((long long)%s_decode_size(_full, _full_sz - %d), -(long long)_full_sz);\n",
                    sc.StructName, ds.Truncate)
            }
        } else {
            fmt.Fprintf(&sb, "        {\n")
            fmt.Fprintf(&sb, "            uint8_t _b[] = {%s};\n", cByteList(ds.Bytes))
            fmt.Fprintf(&sb, "            CHECK_EQ((long long)%s_decode_size(_b, sizeof(_b)), %dLL);\n",
                sc.StructName, ds.Expected)
            fmt.Fprintf(&sb, "        }\n")
        }
    }

    if needSource {
        sb.WriteString("        free(_full);\n")
    }
    sb.WriteString("    }\n")
    return sb.String()
}

func emitC_getterSetter(sc Scenario) string {
    var sb strings.Builder
    fmt.Fprintf(&sb, "/* ============================================================\n")
    fmt.Fprintf(&sb, " * %s — %s\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, " * ============================================================ */\n")
    fmt.Fprintf(&sb, "static void test_%s(void) {\n", scLowerName(sc))
    fmt.Fprintf(&sb, "    g_current = \"%s\";\n", sc.StructName)

    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "    /* case: %s */\n", c.Name)
        fmt.Fprintf(&sb, "    {\n")
        fmt.Fprintf(&sb, "        struct %s s = {0};\n", sc.StructName)
        for _, ap := range c.Accessors {
            fmt.Fprintf(&sb, "        %s_set_%s(&s, %s);\n",
                sc.StructName, ap.SetterName, cFloat(ap.SetArg))
        }
        // Determine if we need round-trip
        roundTrip := false
        for _, ap := range c.Accessors {
            if !ap.NoRoundTrip {
                roundTrip = true
                break
            }
        }
        if roundTrip {
            fmt.Fprintf(&sb, "        uint8_t buf[%s_size];\n", sc.StructName)
            fmt.Fprintf(&sb, "        memset(buf, 0, sizeof(buf));\n")
            fmt.Fprintf(&sb, "        %s_encode(&s, buf);\n", sc.StructName)
            fmt.Fprintf(&sb, "        struct %s d = {0};\n", sc.StructName)
            fmt.Fprintf(&sb, "        CHECK_EQ((int)%s_decode(buf, &d), (int)%s_size);\n",
                sc.StructName, sc.StructName)
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "        CHECK_NEAR(%s_get_%s(&d), %s, %g);\n",
                    sc.StructName, ap.GetterName, cFloat(ap.Expected), tol)
            }
        } else {
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "        CHECK_NEAR(%s_get_%s(&s), %s, %g);\n",
                    sc.StructName, ap.GetterName, cFloat(ap.Expected), tol)
            }
        }
        fmt.Fprintf(&sb, "    }\n")
    }
    sb.WriteString("}\n")
    return sb.String()
}

// ──────────────────────────────────────────────────────────────────────────
// Value formatting
// ──────────────────────────────────────────────────────────────────────────

func cBool(v Val) string {
    if v.U != 0 {
        return "true"
    }
    return "false"
}

func cUInt(v Val) string {
    switch v.Kind {
    case VKU8:
        return fmt.Sprintf("%d", uint8(v.U))
    case VKU16:
        return fmt.Sprintf("%d", uint16(v.U))
    case VKU32:
        return fmt.Sprintf("0x%XU", uint32(v.U))
    case VKU64:
        return fmt.Sprintf("0x%XULL", v.U)
    }
    return fmt.Sprintf("%d", v.U)
}

// cUIntRaw returns the literal w/o the U/ULL suffix (caller adds it).
func cUIntRaw(v Val) string {
    switch v.Kind {
    case VKU32:
        return fmt.Sprintf("0x%X", uint32(v.U))
    case VKU64:
        return fmt.Sprintf("0x%X", v.U)
    }
    return fmt.Sprintf("%d", v.U)
}

func cSInt(v Val) string {
    switch v.Kind {
    case VKI8:
        return fmt.Sprintf("%d", int8(v.I))
    case VKI16:
        return fmt.Sprintf("%d", int16(v.I))
    case VKI32:
        return fmt.Sprintf("%d", int32(v.I))
    case VKI64:
        if v.I == math.MinInt64 {
            return "INT64_MIN"
        }
        return fmt.Sprintf("%dLL", v.I)
    }
    return fmt.Sprintf("%d", v.I)
}

func cFloat(v Val) string {
    if v.Kind == VKF32 {
        return fmt.Sprintf("bb_f32_from_bits(0x%08XU)", uint32(v.U))
    }
    return fmt.Sprintf("bb_f64_from_bits(0x%016XULL)", v.U)
}

func cStringLit(s string) string {
    var sb strings.Builder
    sb.WriteByte('"')
    for _, b := range []byte(s) {
        switch b {
        case '\\':
            sb.WriteString("\\\\")
        case '"':
            sb.WriteString("\\\"")
        case '\n':
            sb.WriteString("\\n")
        case '\r':
            sb.WriteString("\\r")
        case '\t':
            sb.WriteString("\\t")
        default:
            if b < 0x20 || b >= 0x7F {
                fmt.Fprintf(&sb, "\\x%02X\"\"", b)
            } else {
                sb.WriteByte(b)
            }
        }
    }
    sb.WriteByte('"')
    return sb.String()
}

func cByteList(b []byte) string {
    parts := make([]string, len(b))
    for i, v := range b {
        parts[i] = fmt.Sprintf("0x%02X", v)
    }
    return strings.Join(parts, ", ")
}
