package main

import (
    "fmt"
    "math"
    "strings"
)

// EmitCpp produces e2e/tests/cpp/main.cpp from the spec. The output supports
// both the default C++20 span-based API and the legacy non-span API via
// BUBBLER_CPP_COMPAT, mirroring how test_options.sh exercises both.
func EmitCpp(spec *Spec) string {
    var sb strings.Builder

    sb.WriteString(`/*
 * Bubbler E2E Test - C++ target
 *
 * GENERATED by e2e/spec; DO NOT EDIT BY HAND.
 *
 * Build flags toggle the API surface under test:
 *   -DBUBBLER_CPP_SINGLE  : include the .cpp directly (single-file mode)
 *   -DBUBBLER_CPP_COMPAT  : exercise legacy void-pointer API instead of span
 */
#if defined(BUBBLER_CPP_SINGLE)
#include "gen/testpkg.bb.cpp"
#include "gen/bitwid.bb.cpp"
#else
#include "gen/testpkg.bb.hpp"
#include "gen/bitwid.bb.hpp"
#endif

#include <cmath>
#include <cstdio>
#include <cstring>
#include <cstdint>
#include <memory>
#include <string>
#include <vector>

/* ------------------------------------------------------------------ */
/* Minimal test framework                                             */
/* ------------------------------------------------------------------ */
static int g_pass = 0;
static int g_fail = 0;
static const char *g_current = "";

static void _check(bool cond, const char *expr, const char *file, int line) {
    if (cond) {
        ++g_pass;
    } else {
        std::fprintf(stderr, "  FAIL [%s] %s:%d  %s\n", g_current, file, line, expr);
        ++g_fail;
    }
}

#define CHECK(cond)         _check(!!(cond), #cond, __FILE__, __LINE__)
#define CHECK_EQ(a,b)       _check((a)==(b), #a " == " #b, __FILE__, __LINE__)
#define CHECK_NEAR(a,b,eps) _check(std::abs((double)(a)-(double)(b))<(eps), \
                                #a " ~= " #b, __FILE__, __LINE__)

static float bb_f32_from_bits(uint32_t b) { float f; std::memcpy(&f, &b, 4); return f; }
static double bb_f64_from_bits(uint64_t b) { double f; std::memcpy(&f, &b, 8); return f; }
static uint32_t bb_f32_to_bits(float f) { uint32_t b; std::memcpy(&b, &f, 4); return b; }
static uint64_t bb_f64_to_bits(double f) { uint64_t b; std::memcpy(&b, &f, 8); return b; }

using namespace testpkg;

/* ------------------------------------------------------------------ */
/* Encode/decode helpers — pick span vs compat API                    */
/* ------------------------------------------------------------------ */
template <typename T>
static int64_t bb_encode(const T& obj, std::vector<uint8_t>& buf) {
#if defined(BUBBLER_CPP_COMPAT)
    return (int64_t)obj.encode(buf.data());
#else
    return (int64_t)obj.encode(buf);
#endif
}

template <typename T>
static int64_t bb_decode(T& obj, const std::vector<uint8_t>& buf) {
#if defined(BUBBLER_CPP_COMPAT)
    return obj.decode(buf.data());
#else
    return obj.decode(buf);
#endif
}

template <typename T>
static int64_t bb_decode_size(const uint8_t* p, uint64_t n) {
#if defined(BUBBLER_CPP_COMPAT)
    return T::decode_size(p, n);
#else
    return T::decode_size(::std::span<const uint8_t>(p, n));
#endif
}

static struct ::bytes bb_bytes_ref(uint8_t* ptr, uint64_t len) {
    struct ::bytes b;
    b.data = std::shared_ptr<uint8_t[]>(ptr, [](uint8_t*){});
    b.length = len;
    return b;
}

`)

    for _, sc := range spec.Scenarios {
        sb.WriteString(emitCpp_scenario(sc))
        sb.WriteString("\n")
    }

    sb.WriteString("int main() {\n")
    sb.WriteString("    std::printf(\"=== Bubbler E2E Test - C++ ===\\n\\n\");\n")
    for _, sc := range spec.Scenarios {
        sb.WriteString(fmt.Sprintf("    test_%s();\n", scLowerName(sc)))
    }
    sb.WriteString("    std::printf(\"\\n=== Results: %d passed, %d failed ===\\n\", g_pass, g_fail);\n")
    sb.WriteString("    return g_fail > 0 ? 1 : 0;\n")
    sb.WriteString("}\n")
    return sb.String()
}

func emitCpp_scenario(sc Scenario) string {
    if sc.StructName == "GetterSetter" {
        return emitCpp_getterSetter(sc)
    }

    var sb strings.Builder
    fmt.Fprintf(&sb, "/* ============================================================\n")
    fmt.Fprintf(&sb, " * %s — %s\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, " * ============================================================ */\n")
    fmt.Fprintf(&sb, "static void test_%s() {\n", scLowerName(sc))
    fmt.Fprintf(&sb, "    g_current = \"%s\";\n", sc.StructName)

    qual := cppStructQual(sc)

    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "    /* --- case: %s --- */\n", c.Name)
        sb.WriteString("    {\n")
        fmt.Fprintf(&sb, "        %s s{};\n", qual)
        for _, fv := range c.Setup {
            sb.WriteString(emitCpp_assignVal("s."+fv.Name, fv.V, "        "))
        }

        if sc.IsDynamic {
            fmt.Fprintf(&sb, "        std::vector<uint8_t> buf(s.encode_size());\n")
            fmt.Fprintf(&sb, "        int64_t _enc = bb_encode(s, buf);\n")
            fmt.Fprintf(&sb, "        CHECK_EQ((long long)_enc, (long long)buf.size());\n")
        } else {
            fmt.Fprintf(&sb, "        std::vector<uint8_t> buf(%s::size, 0);\n", qual)
            fmt.Fprintf(&sb, "        CHECK_EQ((int)bb_encode(s, buf), (int)%s::size);\n", qual)
        }

        if sc.StructName == "BigEndianFields" {
            sb.WriteString("        CHECK_EQ(buf[0], 0xBE);\n")
            sb.WriteString("        CHECK_EQ(buf[1], 0x12);\n")
            sb.WriteString("        CHECK_EQ(buf[2], 0x34);\n")
        }
        if sc.StructName == "ConstantFields" {
            sb.WriteString("        CHECK_EQ(buf[0], 0xAA);\n")
            sb.WriteString("        CHECK_EQ(buf[1], 0x02);\n")
            sb.WriteString("        CHECK_EQ(buf[4], 0x02);\n")
        }

        fmt.Fprintf(&sb, "        %s d{};\n", qual)
        if sc.IsDynamic {
            sb.WriteString("        int64_t _dec = bb_decode(d, buf);\n")
            sb.WriteString("        CHECK(_dec > 0);\n")
        } else {
            fmt.Fprintf(&sb, "        CHECK_EQ((int)bb_decode(d, buf), (int)%s::size);\n", qual)
        }
        for _, af := range c.resolveAssert() {
            sb.WriteString(emitCpp_assertVal("d."+af.Name, af.V, af.Tol, "        "))
        }

        for _, e := range c.Errors {
            fmt.Fprintf(&sb, "        /* decode-error: %s */\n", e.Name)
            sb.WriteString("        {\n")
            sb.WriteString("            std::vector<uint8_t> bad = buf;\n")
            for _, p := range e.Patches {
                fmt.Fprintf(&sb, "            bad[%d] = 0x%02X;\n", p.Offset, p.Value)
            }
            fmt.Fprintf(&sb, "            %s err{};\n", qual)
            fmt.Fprintf(&sb, "            CHECK_EQ((long long)bb_decode(err, bad), %dLL);\n", e.ExpectedRet)
            sb.WriteString("        }\n")
        }
        sb.WriteString("    }\n")
    }

    if len(sc.DecodeSizeChecks) > 0 {
        sb.WriteString(emitCpp_decodeSize(sc))
    }

    sb.WriteString("}\n")
    return sb.String()
}

func cppStructQual(sc Scenario) string {
    if sc.Package == "bitwid" {
        return "bitwid::" + sc.StructName
    }
    return sc.StructName
}

func emitCpp_assignVal(dst string, v Val, indent string) string {
    switch v.Kind {
    case VKBool:
        return fmt.Sprintf("%s%s = %s;\n", indent, dst, cBool(v))
    case VKU8, VKU16, VKU32, VKU64:
        return fmt.Sprintf("%s%s = %s;\n", indent, dst, cUInt(v))
    case VKI8, VKI16, VKI32, VKI64:
        return fmt.Sprintf("%s%s = %s;\n", indent, dst, cSInt(v))
    case VKF32:
        return fmt.Sprintf("%s%s = bb_f32_from_bits(0x%08XU);\n", indent, dst, uint32(v.U))
    case VKF64:
        return fmt.Sprintf("%s%s = bb_f64_from_bits(0x%016XULL);\n", indent, dst, v.U)
    case VKEnum:
        return fmt.Sprintf("%s%s = %s::%s;\n", indent, dst, v.EnumType, v.EnumName)
    case VKString:
        return fmt.Sprintf("%s%s = std::string(%s);\n", indent, dst, cStringLit(v.Str))
    case VKBytes:
        var sb strings.Builder
        if len(v.Bytes) == 0 {
            fmt.Fprintf(&sb, "%s%s = bb_bytes_ref(nullptr, 0);\n", indent, dst)
            return sb.String()
        }
        fmt.Fprintf(&sb, "%s{\n", indent)
        fmt.Fprintf(&sb, "%s    static uint8_t _b[] = {%s};\n", indent, cByteList(v.Bytes))
        fmt.Fprintf(&sb, "%s    %s = bb_bytes_ref(_b, sizeof(_b));\n", indent, dst)
        fmt.Fprintf(&sb, "%s}\n", indent)
        return sb.String()
    case VKStruct:
        var sb strings.Builder
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitCpp_assignVal(dst+"."+f.Name, f.V, indent))
        }
        return sb.String()
    case VKArray:
        var sb strings.Builder
        for i, item := range v.Array.Items {
            sb.WriteString(emitCpp_assignVal(fmt.Sprintf("%s[%d]", dst, i), item, indent))
        }
        return sb.String()
    }
    return ""
}

func emitCpp_assertVal(dst string, v Val, tol float64, indent string) string {
    switch v.Kind {
    case VKBool:
        return fmt.Sprintf("%sCHECK_EQ(%s, %s);\n", indent, dst, cBool(v))
    case VKU8, VKU16:
        return fmt.Sprintf("%sCHECK_EQ((int)%s, %s);\n", indent, dst, cUInt(v))
    case VKU32:
        return fmt.Sprintf("%sCHECK_EQ((uint32_t)%s, %sU);\n", indent, dst, cUIntRaw(v))
    case VKU64:
        return fmt.Sprintf("%sCHECK_EQ((uint64_t)%s, %sULL);\n", indent, dst, cUIntRaw(v))
    case VKI8, VKI16, VKI32:
        return fmt.Sprintf("%sCHECK_EQ((int64_t)%s, (int64_t)%s);\n", indent, dst, cSInt(v))
    case VKI64:
        return fmt.Sprintf("%sCHECK_EQ((long long)%s, (long long)%s);\n", indent, dst, cSInt(v))
    case VKF32:
        if tol > 0 {
            return fmt.Sprintf("%sCHECK_NEAR(%s, bb_f32_from_bits(0x%08XU), %g);\n",
                indent, dst, uint32(v.U), tol)
        }
        return fmt.Sprintf("%sCHECK_EQ((unsigned long)bb_f32_to_bits(%s), 0x%08XUL);\n",
            indent, dst, uint32(v.U))
    case VKF64:
        if tol > 0 {
            return fmt.Sprintf("%sCHECK_NEAR(%s, bb_f64_from_bits(0x%016XULL), %g);\n",
                indent, dst, v.U, tol)
        }
        return fmt.Sprintf("%sCHECK_EQ((unsigned long long)bb_f64_to_bits(%s), 0x%016XULL);\n",
            indent, dst, v.U)
    case VKEnum:
        return fmt.Sprintf("%sCHECK(%s == %s::%s);\n", indent, dst, v.EnumType, v.EnumName)
    case VKString:
        return fmt.Sprintf("%sCHECK(%s == std::string(%s));\n", indent, dst, cStringLit(v.Str))
    case VKBytes:
        var sb strings.Builder
        fmt.Fprintf(&sb, "%sCHECK_EQ((int)%s.length, %d);\n", indent, dst, len(v.Bytes))
        if len(v.Bytes) > 0 {
            fmt.Fprintf(&sb, "%s{\n", indent)
            fmt.Fprintf(&sb, "%s    static const uint8_t _exp[] = {%s};\n", indent, cByteList(v.Bytes))
            fmt.Fprintf(&sb, "%s    CHECK(std::memcmp(%s.data.get(), _exp, sizeof(_exp)) == 0);\n", indent, dst)
            fmt.Fprintf(&sb, "%s}\n", indent)
        }
        return sb.String()
    case VKStruct:
        var sb strings.Builder
        for _, f := range v.Struct.Fields {
            sb.WriteString(emitCpp_assertVal(dst+"."+f.Name, f.V, tol, indent))
        }
        return sb.String()
    case VKArray:
        var sb strings.Builder
        for i, it := range v.Array.Items {
            sb.WriteString(emitCpp_assertVal(fmt.Sprintf("%s[%d]", dst, i), it, tol, indent))
        }
        return sb.String()
    }
    return ""
}

func emitCpp_decodeSize(sc Scenario) string {
    qual := cppStructQual(sc)
    var sb strings.Builder
    sb.WriteString("    /* --- decode_size boundary checks --- */\n")
    sb.WriteString("    {\n")

    var needSource bool
    var srcCase string
    for _, ds := range sc.DecodeSizeChecks {
        if ds.SourceCase != "" {
            needSource = true
            srcCase = ds.SourceCase
        }
    }
    if needSource {
        var c Case
        for _, cc := range sc.Cases {
            if cc.Name == srcCase {
                c = cc
                break
            }
        }
        fmt.Fprintf(&sb, "        %s _src{};\n", qual)
        for _, fv := range c.Setup {
            sb.WriteString(emitCpp_assignVal("_src."+fv.Name, fv.V, "        "))
        }
        sb.WriteString("        std::vector<uint8_t> _full(_src.encode_size());\n")
        sb.WriteString("        bb_encode(_src, _full);\n")
    }
    for _, ds := range sc.DecodeSizeChecks {
        fmt.Fprintf(&sb, "        /* %s */\n", ds.Name)
        if ds.SourceCase != "" {
            if ds.Truncate == 0 {
                fmt.Fprintf(&sb, "        CHECK_EQ((long long)bb_decode_size<%s>(_full.data(), _full.size()), (long long)_full.size());\n",
                    qual)
            } else {
                fmt.Fprintf(&sb, "        CHECK_EQ((long long)bb_decode_size<%s>(_full.data(), _full.size() - %d), -(long long)_full.size());\n",
                    qual, ds.Truncate)
            }
        } else {
            sb.WriteString("        {\n")
            fmt.Fprintf(&sb, "            uint8_t _b[] = {%s};\n", cByteList(ds.Bytes))
            fmt.Fprintf(&sb, "            CHECK_EQ((long long)bb_decode_size<%s>(_b, sizeof(_b)), %dLL);\n",
                qual, ds.Expected)
            sb.WriteString("        }\n")
        }
    }
    sb.WriteString("    }\n")
    return sb.String()
}

func emitCpp_getterSetter(sc Scenario) string {
    var sb strings.Builder
    fmt.Fprintf(&sb, "/* ============================================================\n")
    fmt.Fprintf(&sb, " * %s — %s\n", sc.StructName, sc.Notes)
    fmt.Fprintf(&sb, " * ============================================================ */\n")
    fmt.Fprintf(&sb, "static void test_%s() {\n", scLowerName(sc))
    fmt.Fprintf(&sb, "    g_current = \"%s\";\n", sc.StructName)

    for _, c := range sc.Cases {
        fmt.Fprintf(&sb, "    /* case: %s */\n", c.Name)
        sb.WriteString("    {\n")
        fmt.Fprintf(&sb, "        %s s{};\n", sc.StructName)
        for _, ap := range c.Accessors {
            fmt.Fprintf(&sb, "        s.set_%s(%s);\n", ap.SetterName, cFloat(ap.SetArg))
        }
        roundTrip := false
        for _, ap := range c.Accessors {
            if !ap.NoRoundTrip {
                roundTrip = true
                break
            }
        }
        if roundTrip {
            fmt.Fprintf(&sb, "        std::vector<uint8_t> buf(%s::size, 0);\n", sc.StructName)
            sb.WriteString("        bb_encode(s, buf);\n")
            fmt.Fprintf(&sb, "        %s d{};\n", sc.StructName)
            fmt.Fprintf(&sb, "        CHECK_EQ((int)bb_decode(d, buf), (int)%s::size);\n", sc.StructName)
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "        CHECK_NEAR(d.get_%s(), %s, %g);\n",
                    ap.GetterName, cFloat(ap.Expected), tol)
            }
        } else {
            for _, ap := range c.Accessors {
                tol := ap.Tol
                if tol <= 0 {
                    tol = 1e-9
                }
                fmt.Fprintf(&sb, "        CHECK_NEAR(s.get_%s(), %s, %g);\n",
                    ap.GetterName, cFloat(ap.Expected), tol)
            }
        }
        sb.WriteString("    }\n")
    }
    sb.WriteString("}\n")
    return sb.String()
}

// avoid unused import
var _ = math.Pi
